### ISSUE TITLE
Asset not found scss

### ISSUE THREAD

**Issue by Arueilen** [halt-hammerzeit/webpack-isomorphic-tools#100]
Hi,

when i run my project (which use the react-redux-universal-hot-example boilerplace), i have this error message:

```
[webpack-isomorphic-tools] [error] asset not found: ./src/account/accountForm/personalInformations/PersonalInformations.scss
```

when I require('./PersonalInformations.scss') In ./src/account/accountForm/personalInformations/PersonalInformations.js.

However, this path is correct.

I think it's because in my webpack-asset.json there are:

```
"./src/account/AccountForm/PersonalInformations/PersonalInformations.scss": {
      "header": "header___1prT_",
      "clearFix": "clearFix___235NT",
      "flexBox": "flexBox___1cV5z",
      "contentForm": "contentForm___23xtz",
      "checkboxNameIsDifferent": "checkboxNameIsDifferent___2Mjfv",
      "inputNameIsDifferent": "inputNameIsDifferent___228BN",
      "dirty": "dirty___3Mmsl",
      "focused": "focused___2t-tS",
      "selectBox": "selectBox___nvIeW",
      "nextButton": "nextButton___1YKvH",
    },
```

which is not in the same case.
I don't know how to fix it.

Have you an idea ?
I'm on El Capitan but it's the same on Ubuntu 14

**Comment by halt-hammerzeit** [comment]
Is the folder name `AccountForm` or `accountForm`?
I don't know why the cases are different.

**Comment by Arueilen** [comment]
Folder name is accountForm

**Comment by halt-hammerzeit** [comment]
You can try to add `path` parser to `scss` assets:

```
path(module, options, log)
{
    log.info('====================== module', module)
    return module.name
}
```

And post the output

**Comment by halt-hammerzeit** [comment]
Alternatively you can run it in `debug` mode and post the generated `webpack-stats.json`.
