### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by peter-mouland** [halt-hammerzeit/webpack-isomorphic-tools#104]
apologies, I don't think this is a bug, I am struggling to get this to work server-side.  Im sure i've just got a path wrong or missed some config. 

On the server, I am getting a `React is not defined` error.

Here is a small project example I am trying to integrate with it:
https://github.com/peter-mouland/react-lego/compare/svg

any help or pointers would be much appreciated.

**Comment by halt-hammerzeit** [comment]
`React is not defined` means you didn't do `import React from 'react'` in all your React components.

**Comment by peter-mouland** [comment]
It isn't as straight-forward as that unfortunately.

It is coming from the `.svg` file : 
```sh

ReferenceError: React is not defined
    at Object.<anonymous> (/Users/peterm/Workspace/personal/react-lego/src/app/containers/Game/assets/chevron.svg:1:1)

```

This is why i think the setup for isomorphic-tools must be missing something

**Comment by halt-hammerzeit** [comment]
Well, you wrote your `parser` for `svg` and it parses the file contents to something which requires React.
```js
parser(module) {
+        if (module.source) {
+          const regex = /module\.exports = "((.|\n)*)"/;
+          const match = module.source.match(regex);
+          return (match ? match[1] : '').replace(/\\/g, '');
+        }
+      }
```

I would treat SVG as any other picture format like jpg.
So I wouldn't use any loader for it.

You can post your `webpack-assets.json`

**Comment by peter-mouland** [comment]
thanks for the reply, removing my custom parser (which I have used in other projects), still returns the same results.

here is the json file requested : 

```json
{"javascript":{"app":"/app.js"},"styles":{"app":"/app.css"},"assets":{"./src/app/containers/Game/assets/chevron.svg":"<svg viewBox=\"0 0 100 60\" xmlns=\"http://www.w3.org/2000/svg\" class=\"n-icon n-icon--chevron\"><g class=\"n-icon__group\"><line class=\"n-icon__fg n-icon__line n-icon__line--left\" x1=\"50\" y1=\"50\" x2=\"10\" y2=\"10\" stroke-width=\"15\" stroke-linecap=\"round\"></line><line class=\"n-icon__fg n-icon__line n-icon__line--right\" x1=\"50\" y1=\"50\" x2=\"90\" y2=\"10\" stroke-width=\"15\" stroke-linecap=\"round\"></line></g></svg>"}}
```

**Comment by halt-hammerzeit** [comment]
Well, I don't know then, why is it complaining about React, because it uses no React in this case.

**Comment by peter-mouland** [comment]
just to complete this issue, it was because the server code was being required before the isomorphic-tools server had started. 

i.e. https://github.com/peter-mouland/react-lego/compare/svg#diff-8f22dd83b0754a205d97fb9f26e937e2R16
