### ISSUE TITLE
would provide a link to my example project?

### ISSUE THREAD

**Issue by peter-mouland** [halt-hammerzeit/webpack-isomorphic-tools#105]
I'm currently working on an example project,https://github.com/peter-mouland/react-lego, that will hopefully help developers add new techs (like webpack-isomorphic-tools) to their React projects.  

The reason why I started the project was because although, I could find many, many boilerplates which included the tech i wanted, they were often built in such different ways it was very difficult to extract just the bits I needed.  the react-lego repo is built in a way that hopefully devs will be able to see just how to add the one bit they are looking for.

If feel it's up to scratch, do you mind linking to this project?  The [importing svgs](https://github.com/peter-mouland/react-lego#importing-svgs) references this project and this link will help show people how webpack-isomorphic-tools was implemented: https://github.com/peter-mouland/react-lego/compare/svg

**Comment by halt-hammerzeit** [comment]
The idea is good.
Although I prefer a more narrative way of explaining things, like tutorials.
Maybe something like egghead videos
https://egghead.io/courses/getting-started-with-redux
Using isomorphic tools is not an easy task and maybe a good tutorial would be appropriate but currently there are no tutorials on this topic.

**Comment by peter-mouland** [comment]
that's valid - i'll see how i can add more conversation around the code changes and get back to you.

**Comment by halt-hammerzeit** [comment]
I think at the point I wouldn't add a diff as an example to this repo (event the commented one).
Maybe I would add a blog post explaining each step or something like that.

**Comment by peter-mouland** [comment]
yeah, thats the conclusion i'm coming to also. 
A blog post to go with each of my branches would help explain the `why` and `how` of each solution i've gone for...

**Comment by peter-mouland** [comment]
as a starter i've add this descriptive page which is linked to from the main readme.md.

https://github.com/peter-mouland/react-lego/wiki/Importing-SVGs

If you spot any errors (especially concerning your project!), let me know and I'll correct them.

I'll look into doing a live coding video, but something tells me this'll be harder than I imagine!

**Comment by halt-hammerzeit** [comment]
Ok, this looks good enough.
I've included the link to your explanation in the README.

I'm not sure if anyone would watch a live coding video: I personally find such videos time consuming and prefer text.
