### ISSUE TITLE
_webpackIsomorphicTools2.default.assets is not a function and missing path with webpack-isomorphic-tools.assets()

### ISSUE THREAD

**Issue by ChazUK** [halt-hammerzeit/webpack-isomorphic-tools#109]
I'm having a bit of trouble getting my SSR working with webpack-isomorphic-tools, so far I've got my build script spitting out the relevant static files and the webpack-assets.json, but on loading the server and trying to pull in the CSS using `WebpackIsomorphicTools.assets()` I get an error:

```
TypeError: _webpackIsomorphicTools2.default.assets is not a function
    at web-app/src/server/server.js:35:40
```

and when trying to use `global.webpack_isomorphic_tools.assets()` I get the error:

```
AssertionError: missing path
    at Module.require (module.js:466:3)
    at require (internal/module.js:20:19)
    at webpack_isomorphic_tools.assets (web-app/node_modules/webpack-isomorphic-tools/source/index.js:100:10)
    at web-app/src/server/server.js:35:49
```

node 6.3.1
npm 3.10.6
babel-core 6.10.4

https://gist.github.com/ChazUK/d3d0f53d2ee1cad8cc1929a6796d4f07

**Comment by halt-hammerzeit** [comment]
No.

First of all, you seem to be new to javascript, because `WebpackIsomorphicTools.assets()` makes no sense.

Second, you messed up the `global.webpack_isomorphic_tools` instance:

```js

global.webpack_isomorphic_tools = new WebpackIsomorphicTools(webpackIsomorphicConfig)
  .development(process.env.NODE_ENV !== 'production')
  .server(base, () => {
    require('./server');
  });
```

```js

global.webpack_isomorphic_tools = new WebpackIsomorphicTools(WebpackIsomorphicConfig)
.development(process.env.NODE_ENV !== 'production');
```

The error means that `this.webpack_assets_path` is `undefined` because it's initialized inside the `.server()` method call and you aren't calling it the second time.

So, the answer is to remove the line from `server.js`

**Comment by halt-hammerzeit** [comment]
By the way, I deprecated `.development()` function so you can drop it

**Comment by halt-hammerzeit** [comment]
EDIT: `.development()` is deprecated for the server-side instance. It's still required for the webpack plugin instance.

**Comment by ChazUK** [comment]
Apologises for my immense stupidity. I'm not _new_ to JavaScript, I'm new to 2016's JavaScript.

Thanks for your help though (Y)

**Comment by ChazUK** [comment]
Whilst we're at it, might as well throw some humour into the mix https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f

**Comment by halt-hammerzeit** [comment]
> I need to display data on a page, not perform Sub Zero’s original MK fatality

Yeah, front-end is overly complicated these days

**Comment by ChazUK** [comment]
Quick Q whilst I'm here, any idea why `app.use('/static', express.static(path.join(__dirname, 'build/static')));` doesn't appear to be loading any static files?

**Comment by halt-hammerzeit** [comment]
It's a tricky one to get paths right.
The code snippet you posted should be working.
