### ISSUE TITLE
ERROR in (webpack)-isomorphic-tools/package.json

### ISSUE THREAD

**Issue by peter-mouland** [halt-hammerzeit/webpack-isomorphic-tools#113]
Hi,

I'm not sure what's changed, possibly not even webpack-isomorphic tools, but for some reason i've started getting this error:

`ERROR in (webpack)-isomorphic-tools/package.json`

It is puzzling, because i've not changed my code and it was working for me perfectly previously.  

have you seen it before?

I have this app where the problem can be reproduced: 
https://github.com/peter-mouland/react-lego/tree/express--svg

The full error is:
<img width="1075" alt="screen shot 2016-10-22 at 14 56 58" src="https://cloud.githubusercontent.com/assets/1727939/19619871/2cf3033a-9868-11e6-9816-691c036e001b.png">

**Comment by halt-hammerzeit** [comment]
That's weird.
Why is it writing `webpack` in parentheses.
Seems that you're `require()`ing `webpack-isomorphic-tools/package.json` (or even `*.json`) somewhere in your code and you haven't set up a webpack loader for `json` extension.
Try adding JSON loader in your webpack configuration.

**Comment by halt-hammerzeit** [comment]
And when you do add JSON loader in Webpack configuration, don't exclude `node_modules/webpack-isomorphic-tools` from it (`include/exclude`).
This might work, but still this `package.json` should not be required I guess.

**Comment by peter-mouland** [comment]
yeah, it is weird because i'm not requiring that file.

Adding the json loader was the first thing i tried.  I reverted the change, because it shouldn't be needed by my code and also because i then got the following error:

<img width="1304" alt="screen shot 2016-10-22 at 17 32 46" src="https://cloud.githubusercontent.com/assets/1727939/19620872/b46def86-987d-11e6-9bf0-c8d095c97f0f.png">

**Comment by peter-mouland** [comment]
if it makes it easier - this is the code added to get webpack-isomorphic-tools to work previously (which now no longer works) https://github.com/peter-mouland/react-lego/compare/express...express--svg

**Comment by halt-hammerzeit** [comment]
I think the `package.json` error arises when `webpack-isomorphic-tools` are `require()`d.

```
const IsomorphicTools = require('webpack-isomorphic-tools');
```

Put `console.log` before and after this line to find out if that's the case.

**Comment by peter-mouland** [comment]
the console.log occur in sequence with no errors in between. The error comes later.

If i comment out the following line from within `write assets.js` the error goes and the app works:
```
log.debug('running write assets webpack plugin v' + require('../../package.json').version + ' with options', options);
```

This error only occurs when i compile my server code using `npm run build:server` from the example repo

**Comment by halt-hammerzeit** [comment]
Oh, there it is...
Ok, I see, so it runs Webpack, applies `webpack-isomorphic-tools/plugin`, executes that line of code and then, for some reason, it tries to bundle `webpack-isomorphic-tools/plugin` into the server bundle.
I don't think `node_modules` should be included inside the server-side bundle.
In my other project I just declare all `node_modules` as `externals`
https://github.com/halt-hammerzeit/universal-webpack/blob/master/source/server%20configuration.js#L65

The other thing is why you even use `webpack-isomorphic-tools` when you're already using `target: node` in the server-side build.
`webpack-isomorphic-tools` shouldn't be needed in this case.

**Comment by halt-hammerzeit** [comment]
(and you shouldn't bundle `webpack-isomorphic-tools/plugin` in your server-side bundle at all)

**Comment by peter-mouland** [comment]
I expect that's the problem then. Thanks for spending the time to walk me through this.
