### ISSUE TITLE
 [webpack-isomorphic-tools] [error] `.development()` method is now deprecated

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [halt-hammerzeit/webpack-isomorphic-tools#114]
Hey Guys.

I'm getting this error after update. How to fix ? :)

**Comment by halt-hammerzeit** [comment]
It tells you right there in the error message.
Set `process.env.NODE_ENV` variable to `production` when running in production mode, otherwise it assumes development mode.

**Comment by Iuriy-Budnikov** [comment]
@halt-hammerzeit thanks

**Comment by diegohaz** [comment]
Does it affects the `options.development` flag passed to `filter`, `path` and `parser` methods? I'm getting `options.development === undefined`.

**Comment by dongcai** [comment]
@halt-hammerzeit Yes, I don't have this issue in production, but how to fix it in DEV? It shows as 'error', so I would like to get rid off that annoying message. I tried to no calling "development()"
```
// webpackIsomorphicToolsPlugin.development()
    webpackIsomorphicToolsPlugin 
```
But it does not seems to be working.
cc: @Iuriy-Budnikov  wondering how did you fix this?

**Comment by Bdragon93** [comment]
Hi guys,

@halt-hammerzeit "Set process.env.NODE_ENV" you mean config in webpack.config?

   `new webpack.DefinePlugin({
      __CLIENT__: true,
      __DEVTOOLS__: true,
      'process.env': {
        NODE_ENV: '"development"',
        BROWSER: JSON.stringify(true),
      },
    }),`

I did it and try to remove ` // webpackIsomorphicToolsPlugin.development()` like @dongcai too. But I still get this error.  

I got this error in production too (npm run start), although pro.config.dev I do not call .development()

My repository: https://github.com/Bdragon93/universal-tutorial

**Comment by halt-hammerzeit** [comment]
Oh, hello everyone.

By saying `process.env.NODE_ENV` I mean Node.js, not Webpack, because `webpack-isomorphic-tools` is ALWAYS run in Node.js environment and never in Webpack compiled code.

The warning message is only output when calling `.development()` on the `webpack-isomorphic-tools` server-side instance.
The `.development()` on the **plugin** (`webpack-isomorphic-tools/plugin`) is NOT deprecated and does NOT output the error message:
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/plugin.js#L98

If you're having the warning message being output when calling `.development()` on `webpack-isomorphic-tools/plugin` then try to upgrade to the latest version because there was an intermediate version when it did output the warning but then I decided it was a premature decision and reverted it back for the plugin.

Does it answer your questions?

**Comment by Bdragon93** [comment]
Hi @halt-hammerzeit ,

I tried to lastest version ( `"webpack-isomorphic-tools": "^2.6.4"` ) and set `NODE_ENV` in package.json before comment.

`"scripts": {
    "dev": "NODE_PATH=./src concurrently --kill-others \"npm run dev-server\" \"npm run webpack-dev-server\"",
    "dev-server": "NODE_ENV=development nodemon --exec babel-node ./server",
    "webpack-dev-server": "NODE_ENV=development babel-node ./server/webpack-dev-server.js"`

I am beginner so sorry if I understood wrong something. 
Thanks

**Comment by halt-hammerzeit** [comment]
@Bdragon93 try `npm install webpack-isomorphic-tools@latest --save` and then try again.
If it won't work (which is unlikely) then post your `package.json` from `node_modules/webpack-isomorphic-tools`.

**Comment by Bdragon93** [comment]
@halt-hammerzeit This is my terminal screen shot.

![screenshot from 2016-11-03 17 47 59](https://cloud.githubusercontent.com/assets/9484412/19963143/af51a988-a1ed-11e6-875b-a26b8091ec12.png)

and here is `package.json` from  `node_modules/webpack-isomorphic-tools` :(

[package.txt](https://github.com/halt-hammerzeit/webpack-isomorphic-tools/files/568724/package.txt)

**Comment by halt-hammerzeit** [comment]
Ok, so you're calling `.development()` in your server-side code.
Just remove it from there and the warning won't be shown.

**Comment by Iuriy-Budnikov** [comment]
@Bdragon93 you need to remove .development() in bin/server.js :)

**Comment by Iuriy-Budnikov** [comment]
@Bdragon93 I think you have used redux hot example...

**Comment by dongcai** [comment]
Thanks @Iuriy-Budnikov Yes. that works.  BTW, I use reduxHotExample, and I think @Bartekus uses it too. :-)
In bin/server.js:
`var WebpackIsomorphicTools = require('webpack-isomorphic-tools');
global.webpackIsomorphicTools = new WebpackIsomorphicTools(require('../webpack/webpack-isomorphic-tools'))
  // .development(__DEVELOPMENT__)
  .server(rootDir, function() {
    require('../src/server');
  });`

**Comment by Bdragon93** [comment]
@halt-hammerzeit @Iuriy-Budnikov thank you so much! I followed a tutorial not redux hot example :D .

**Comment by oyeanuj** [comment]
@Iuriy-Budnikov @halt-hammerzeit Sorry, I'm having a little hard time following between the deprecation and undeprecation. As per @Iuriy-Budnikov's above comment, I have commented out the `.development` line. And I'm using `process.env.NODE_ENV` elsewhere in the code, so I guess that is taken care of as well. Is there anything else that I need to do?

PS. My code is also based off of erikras-redux-hot-example as well :)

**Comment by halt-hammerzeit** [comment]
@oyeanuj Yes, the reason for deprecation was that calling `.development()` method the old way felt kinda weird - there already is an established convention to use `process.env.NODE_ENV === production` as production mode indication.
For the `/plugin` there's no way to remove `.development()` (no way to set `process.env.NODE_ENV`) so for the plugin `.development()` method stays.
