### ISSUE TITLE
Sync-request

### ISSUE THREAD

**Issue by mihirsoni** [halt-hammerzeit/webpack-isomorphic-tools#117]
HI , 

I see we are having dependency  of [sync-request](https://github.com/ForbesLindesay/sync-request), I could see it is not recommended in production, can we have an alternative to this ?

**Comment by halt-hammerzeit** [comment]
I don't see what's your problem

**Comment by mihirsoni** [comment]
@halt-hammerzeit I don't have any problem in that , just was lil concerned , do we have any alternative as the owner says it is not meant to run on production as it may create some difficulty to scale.

**Comment by halt-hammerzeit** [comment]
It's only used in developer mode

**Comment by mihirsoni** [comment]
@halt-hammerzeit  Thanks for clarification , i question because it was mentioned under deps. :)
