### ISSUE TITLE
Questions of Babel Compilation

### ISSUE THREAD

**Issue by dtothefp** [halt-hammerzeit/webpack-isomorphic-tools#12]
This is a question around use of `webpack-isomorphic-tools` and compilation through babel vs. use of the `babel/register`. 

I have a script that runs similar to the original demo I shared https://github.com/dtothefp/isomorphic-demo/blob/master/app/index.js. Unfortunately, it is on a private repo so I can't share it here.

Essentially, it uses the `babel/register` and kicks off the process of rendering HTML from a React component. The problem is that this react component `import`s many internal modules (on our internal NPM registry, some of which are themselves react component libraries) that are written in es6 and NOT pre-compiled. I wrote a small script that uses the babel `ignore` property to include these external modules in es6 compilation https://babeljs.io/docs/usage/require/#specifying-options and this works great locally, the HTML compiles in about 2 seconds or less.

The problem is we are running this on an AWS lamda, and in that environment, `import`ing the component results in compile times greater than 30s. I would like to pre-compile the modules or potentially pre-compile the whole script that contains the `webpack-isomorphic-tools` entry i.e.

```js
  tools.development(isDev).server(statsDir).then(() => {
    const runLambda = require('./lambda-function');
     runLambda(templatingArgs, cb);
  });
```
I'm just wondering if this breaks some of the `require` magic or if `require` hooks will still be established regardless by `webpack-isomorphic-tools` if code is pre-compiled through babel and not run through the `babel/register`?

**Comment by halt-hammerzeit** [comment]
`webpack-isomorphic-tools` should work irrelevant of whether you're using Babel or not.
It should be agnostic.

**Comment by dtothefp** [comment]
ok great, also does it not matter if I make the `tools.development(isDev).server(statsDir)` call in the same file that `require`s the `babel/register` as long as creating my HTML is inside of the Promise resolve/callback for the `server` function?

**Comment by halt-hammerzeit** [comment]
As I've already said, `webpack-isomorphic-tools` should work irrelevant of whether you're using Babel or not.
It should be agnostic of whatever code you're putting it in.

**Comment by dtothefp** [comment]
cool thx, closing
