### ISSUE TITLE
webpack-assets.json content becomes wrong on subsequent builds in watch mode

### ISSUE THREAD

**Issue by vjancik** [halt-hammerzeit/webpack-isomorphic-tools#122]
I am using *webpack-isomorphic-tools* alongside *ExtractTextPlugin* in production.
And I also use the `--watch` parameter with the production config for developing, with emitting files, so that my `sw-precache` script works correctly (requires assets on disk to generate the service-worker correctly).

On the first build (when I start the script) the `webpack-assets.json` contains:
  1. my javascript assets paths
  2. my styles assets paths
  3. my inlined & emitted assets (so either content, or asset path) (**PNG**s, **SVG**s)
  4. `// removed by extract-text-webpack-plugin` **SCSS** assets
  5. Again my **SCSS** assets, but **with the actual content**, and the asset key is prefixed with the loaders: e.g. `./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/client/components/XXX/XXX.scss`

On subsequent builds (when I change something, and the --watch parameter rebuilds the bundle) the `webpack-assets.json` contains:
All of the above, without: **5.** All of the inlined **SCSS** files content gets removed from `webpack-assets.json`, only the *// removed by ... bla bla bla* remains
and oddly enough, 1 inlined **SVG** and 1 emitted **SVG** are also missing.

Now the question is, which one of these versions of this file is the correct one?
Because I am depending on the contents of the **SCSS** files being in the **JSON** file, for SSR of critical CSS.

**Versions:**
- extract-text-webpack-plugin@2.0.0-beta.4
- webpack@2.1.0-beta.27

**Comment by halt-hammerzeit** [comment]
> 4. // removed by extract-text-webpack-plugin SCSS assets
5. Again my SCSS assets, but with the actual content, and the asset key is prefixed with the loaders: e.g. ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/client/components/XXX/XXX.scss

This is a symtom of you using CSS modules feature and setting up `webpack-isomorphic-tools.js` incorrectly for `scss` asset type (mainly, the `path` parser).
See the readme for CSS modules example.
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#style-loader-css-stylesheets-with-css-modules-feature
