### ISSUE TITLE
Explain how to make SSR

### ISSUE THREAD

**Issue by yoihito** [halt-hammerzeit/webpack-isomorphic-tools#123]
Hi guys, how can i achieve alternative solution?

> An alternative solution exists now: to compile server-side code with Webpack the same way it already compiles the client-side code. This is the officially recommended way to go and one can use universal-webpack library to achieve that. However, some people still prefer this (earlier) library, so it still exists.

I would like to optimize my build time and it seems to me that `webpack-isomorphic-tools` is a bottleneck in my build.

**Comment by halt-hammerzeit** [comment]
You can achieve the alternative solution by using `universal-webpack` instead.
