### ISSUE TITLE
Unexpected token >

### ISSUE THREAD

**Issue by eddievagabond** [halt-hammerzeit/webpack-isomorphic-tools#130]
My project is compiling and running correctly in development mode, but in the chrome console I see the following. 
<img width="810" alt="ss" src="https://cloud.githubusercontent.com/assets/15243156/22891410/e88d96d0-f1d4-11e6-80b0-6b35a1c7bba3.png">

When I look at the source, I am seeing the generated html from my html.jsx page. I do not understand why this is happening. Is there a simple example repo with server and dev builds. Every example I look at has been outdated or doesn't run properly. Any help would be much appreciated.

**Comment by halt-hammerzeit** [comment]
Yes, there is an example repo and it's in the readme
https://github.com/halt-hammerzeit/webapp

**Comment by halt-hammerzeit** [comment]
The reason you're seeing "Unexpected token <" is because you don't serve `app-....js` file and intead return a 404 Not found HTML page hence the error mesage

**Comment by eddievagabond** [comment]
I'm not entirely sure what you mean. The application is returned and running in the browser. The js files are generated correctly by webpack and added as scripts to the template. Maybe I am misunderstanding how this is supposed to work.

**Comment by halt-hammerzeit** [comment]
@eddievagabond you surely are

**Comment by eddievagabond** [comment]
I'll try again from the beginning. Thanks for the help.

**Comment by halt-hammerzeit** [comment]
Perhaps you should look at `universal-webpack` instead.
It has a much simple example project: https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
