### ISSUE TITLE
webpack-assets lifecycle

### ISSUE THREAD

**Issue by eseom** [halt-hammerzeit/webpack-isomorphic-tools#133]
I'am working on hapi-react-fullstack-boilerplate.
Once I reruns dev command, sometimes the server uses previous webpack-assets.json.
Added ```rm webpack-assets.json``` to every dev server command, It solves the problem, but I don't know whether this makes problem.

[here is a link](https://github.com/eseom/hapi-react-fullstack-boilerplate/blob/master/package.json#L49)

Where I could find documetation about that?
Thanks for nice package.

**Comment by halt-hammerzeit** [comment]
`dev` waits for `webpack-assets.json` to exist.
one can optionally erase this file every time running the `dev` command.
this is not considered a problem.
