### ISSUE TITLE
Not compatible with webpack 3

### ISSUE THREAD

**Issue by damien916** [halt-hammerzeit/webpack-isomorphic-tools#142]
Hello, 

Since I upgrade webpack from 2.6 to 3, "assets" object in webpack-assets.json remain empty.

I think the problem come from style_loader_filter which verify "/~/..." 
Since Webpack 3, node_modules no longer mangle to ~ in stats (see https://github.com/webpack/webpack/releases)

module.name is now 
`name: './node_modules/css-loader!./node_modules/postcss-loader/lib?{}!./node_modules/less-loader/dist!./common/app/Layout/Product/styles/visuals.less',
`

Temporarily, i will use my own filter function in config file.

Bye, and thank you for your job 👍

**Comment by stevez86** [comment]
@damien916 care to share your webpack config with the filter function that gets around this?

**Comment by halt-hammerzeit** [comment]
@damien916 good job figuring out the source of the bug.
I modified the library to include webpack version in `webpack-assets.json`.
When using Webpack 3 now it doesn't replace `node_modules` with `~` inside `webpack-assets.json`.
See if the latest version works.

**Comment by damien916** [comment]
Hello @halt-hammerzeit, thank you, it's perfect !
