### ISSUE TITLE
Unexpected token less file

### ISSUE THREAD

**Issue by mustaqball** [halt-hammerzeit/webpack-isomorphic-tools#167]
I want to start a new big project where I am not using isomorphic/universal-webpack or next.js, how can I get the required call on the server-side to work?

**Comment by catamphetamine** [comment]
> how can I get the require call on the server side to work?

Only `*.js` / `*.json` requires work on server side.
Anything more than that requires using a bundler like Webpack, or a framework that uses a bundler internally.

**Comment by mustaqball** [comment]
I use webpack v5, but how to return the real path to the image or css on the disk on SSR?

**Comment by catamphetamine** [comment]
By using a `file-loader`.
They seem to have renamed it to something else in v5, like "webpack assets".

**Comment by mustaqball** [comment]
This is for the client-side, but what about the server-side?

**Comment by catamphetamine** [comment]
This is for the server side

**Comment by catamphetamine** [comment]
They had `target: "node"` parameter or something like that.
