### ISSUE TITLE
asset not found

### ISSUE THREAD

**Issue by CalebEverett** [halt-hammerzeit/webpack-isomorphic-tools#24]
I installed [react-toolbox] (https://github.com/react-toolbox/react-toolbox) in [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) and got this error:

```
[1] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/app/style.scss
[1] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/app_bar/style.scss
[1] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/input/style.scss
[1] [webpack-isomorphic-tools] [error] asset not found: ./~/react-toolbox/lib/font_icon/style.scss
[1] [piping] can't execute file: D:\projects\rrum\bin\server.js
[1] [piping] error given was: Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr [1]     at proxyReactComponents (D:\projects\rrum\node_modules\react-transform-hmr\lib\index.js:51:11)
[1]     at Object.<anonymous> (D:\projects\rrum\node_modules\react-toolbox\lib\input\index.js:45:65)
[1]     at Module._compile (module.js:435:26)
[1]     at Module._extensions..js (module.js:442:10)
[1]     at Object.require.extensions.(anonymous function) [as .js] (D:\projects\rrum\node_modules\babel-core\lib\api\register\node.js:214:7)
[1]     at Module.load (module.js:356:32)
[1]     at Module._load (module.js:311:12)
[1]     at Function.module._load (D:\projects\rrum\node_modules\piping\lib\launcher.js:32:16)
[1]     at Module.require (module.js:366:17)
[1]     at require (module.js:385:17)

**Comment by halt-hammerzeit** [comment]
Well, if asset is not found then it's not present in `webpack-assets.json`, which means you didn't place it there.
As for the exception I don't know what it means and it tells something about Babel and HMR

**Comment by CalebEverett** [comment]
Thank you. Any suggestions on how to put them there? the .scss files are being required in the components that are imported from node_modules.

**Comment by halt-hammerzeit** [comment]
I've updated the docs:
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#what-are-webpack-assetsjson
This section now contains the answer to your question.
Be there more questions - ask

**Comment by halt-hammerzeit** [comment]
Also revise the "What's a module?" section as I've rewritten it too
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#whats-a-module

**Comment by CalebEverett** [comment]
Thanks very much, that helps a lot. This may be a question more appropriate for the react-redux-universal guys, but do you know where do the arguments to the filter they have set up in their isomorphic tools config file get passed in from? Does isomorphic tools pick those up from the modules as they run through the loaders or do they come from the webpack config?

```javascript
    style_modules: {
      extensions: ['less','scss'],
      filter: function(module, regex, options, log) {
        if (options.development) {
          // in development mode there's webpack "style-loader",
          // so the module.name is not equal to module.name
          return WebpackIsomorphicToolsPlugin.style_loader_filter(module, regex, options, log);
        } else {
          // in production mode there's no webpack "style-loader",
          // so the module.name will be equal to the asset path
          return regex.test(module.name);
        }
      },
```

**Comment by halt-hammerzeit** [comment]
As configuration section says
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#configuration
`module` is the module from webpack stats.
options are some options (described there too).
All these parameters are managed by `webpack-isomorphic-tools`

**Comment by Khodeir** [comment]
@CalebEverett, did you ever get react-toolbox working on react-redux-universal-hot-example? Was it a webpack-isomorphic-tools configuration issue? I'm facing the same issue.

**Comment by CalebEverett** [comment]
No, sorry I couldn't figure it out and moved on and that was a while ago so
my memory on it isn't that great. One thing I remember working to solve the
asset not found issue a couple of other times was to change the environment
to production and build it all the way and then switch back to development.

On Tue, May 10, 2016 at 10:17 AM, Mohamed Khodeir <notifications@github.com>
wrote:

> @CalebEverett <https://github.com/CalebEverett>, did you ever get
> react-toolbox working on react-redux-universal-hot-example? Was it a
> webpack-isomorphic-tools configuration issue? I'm facing the same issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/halt-hammerzeit/webpack-isomorphic-tools/issues/24#issuecomment-218227467>
>



-- 
Caleb Everett
Career College of California
201 E. 4th Street, Suite 200
Santa Ana, CA 92701
(714) 243-8614 phone and fax
www.careercalifornia.edu

Facebook <http://www.facebook.com/CareerCalifornia> | Twitter
<http://twitter.com/careercalif> |  LinkedIn
<http://www.linkedin.com/company/941062> | G+
<https://plus.google.com/b/104968762557101611990/104968762557101611990/posts>

**Comment by halt-hammerzeit** [comment]
> One thing I remember working to solve the
asset not found issue a couple of other times was to change the environment
to production and build it all the way and then switch back to development.

Of course, because `build it all the way` generates `webpack-assets.json` which aren't generated in your development mode due to misconfiguration.
