### ISSUE TITLE
Support webpack resolve.modulesDirectories

### ISSUE THREAD

**Issue by fubhy** [halt-hammerzeit/webpack-isomorphic-tools#28]
https://github.com/erikras/react-redux-universal-hot-example currently uses NODE_PATH to get around that more or less (despite using NODE_PATH actually being actively discouraged by the Node community). 

But it's still not as powerful as webpacks modulesDirectories which basically travels up the directory hierarchy until it finds one of the given directory names at which point it starts looking for the given module inside it.

Are there any plans for supporting webpack's resolve.modulesDirectories?

**Comment by halt-hammerzeit** [comment]
info
http://webpack.github.io/docs/configuration.html#resolve-modulesdirectories

why are you using anything other than `node_modules`?

**Comment by fubhy** [comment]
Because I have a rather huge application and don't want to keep writing ../../../../ in my imports ;). My directory structure is inspired by this: https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346#file-folder-structure-md and I am trying to get the 'shared' part working.

**Comment by halt-hammerzeit** [comment]
I still don't understand.
Give me some code.

**Comment by halt-hammerzeit** [comment]
So, you use a `shared` folder as a `node_modules` kind of thing?
I get it now.

**Comment by fubhy** [comment]
Yep, basically I am directing my import statements to look in 'shared' (anywhere up in the directory hierarchy from the current file path) before looking in node modules. That enables me to write 

```javascript
import foo from 'bar'; 
```

instead of writing
```javascript
import foo from '../../../../shared/bar; 
```

**Comment by fubhy** [comment]
```javascript
  resolve: {
    modulesDirectories: ['shared', 'node_modules'],
    extensions: ['', '.js']
  },
```
This is the relevant part from my webpack config.

**Comment by halt-hammerzeit** [comment]
Ok.
The function to be rewritten is `Module._nodeModulePaths`
https://github.com/nodejs/node/blob/master/lib/module.js#L190-L208
Specifically, this line:
https://github.com/nodejs/node/blob/master/lib/module.js#L203-L204

It will be changed into:
```javascript
modulesDirectories.forEach(function(directory)
{
    var dir = parts.slice(0, tip + 1).concat(directory).join(path.sep);
    paths.push(dir);
})
```

And it should work.

Currently I don't see much need in supporting that `modulesDirectories` option but you can make a Pull Request if you want to implement it (as per the instructions I gave above). It will:

* add `modulesDirectories` parameter to the configuration
* validate that parameter in `common.js`
* if that parameter exists and is valid, it will replace `Module._nodeModulePaths` with the new one (with the loop)
* if `Module._nodeModulePaths` doesn't exist it will throw an Error
* a test for the `modulesDirectories` case will be needed in the `tests` folder
* documentation README.md will be updated

**Comment by halt-hammerzeit** [comment]
Oh, and that's not all of that.
It only handles the default `*.js` `requre()` calls.
The other part is `require()` calls for the assets:
presumably `normalize_asset_path` function will be modified to transform those `shared/...` `require()` paths into the paths relevant to the project root folder (`normalized` ones).

Maybe there will be something else.

**Comment by fubhy** [comment]
Glad that you are not opposed to the idea. Sounds like a plan then... I'll not be able to do this until mid-end next week but will get back to it then as I badly need this for my current project (really don't want to go back to these crazy ../../../ imports). Thanks!

**Comment by halt-hammerzeit** [comment]
(closing for now)

**Comment by huchenme** [comment]
+1

**Comment by halt-hammerzeit** [comment]
@huchenme ok, since more that one user would like that feature I can try to implement it.

Try out the new version
`webpack-isomorphic-tools@2.2.29`

Add `modulesDirectories` parameter to the configuration.

And tell me if it works.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
