### ISSUE TITLE
does not write webpack-assets.json to location specified as rootDir

### ISSUE THREAD

**Issue by bdefore** [halt-hammerzeit/webpack-isomorphic-tools#30]
Following the example here: https://github.com/erikras/react-redux-universal-hot-example/blob/master/bin/server.js#L4 I'm attempting to change `rootDir` to another path, in order to better externalize my source from the boilerplate code. For example, I'd like to change that to `var rootDir = path.resolve(__dirname, '../external');` I also then update the `context` to point to the same path, so that the tools can find the `webpack-assets.json`.

Unfortunately, what I see is that it is writing the file into the project root, rather than what I'm specifying.

If I add logs to here: https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/index.js#L149

```
		console.log('setting up project path', this.options.project_path);
		console.log('setting up webpack assets path', this.webpack_assets_path);
```

I get the following output:

```
[1] setting up project path /Users/d4/code/react-redux-universal-hot-example-fork/external
[1] setting up webpack assets path /Users/d4/code/react-redux-universal-hot-example-fork/external/webpack-assets.json
```

But then `webpack-assets.json` is written to the project root and it never finds them, so I see endless logs like the following:

```
[1] [webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
```

I'm running version 2.2.18

**Comment by halt-hammerzeit** [comment]
`webpack-assets.json` is written by Webpack plugin therefore `rootDir` doesn't take effect because `rootDir` variable is used only in your server code.
Does this answe your question?

**Comment by bdefore** [comment]
how would i configure where that gets written to?

**Comment by halt-hammerzeit** [comment]
you can use the configuration:
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#configuration
`webpack_assets_file_path`

**Comment by bdefore** [comment]
thanks. i got it to work by specifying `webpack_assets_file_path: 'external/webpack-assets.json',` in that configuration.

a note though: at that link it says in your comments above that it would default to writing webpack-assets.json the webpack configuration context, which i am setting to my `external` directory, so i would have expected this change to be unnecessary.

**Comment by halt-hammerzeit** [comment]
> a note though: at that link it says in your comments above that it would default to writing webpack-assets.json the webpack configuration context, which i am setting to my external directory, so i would have expected this change to be unnecessary.

Well, it did create `webpack-assets.json` in your webpack configuration context folder, or didn't it?

**Comment by bdefore** [comment]
without the additional configuration change to `webpack_assets_file_path` it did not, it would right to `webpack-assets.json` to the project root even though Webpack context was configured to `external`

**Comment by halt-hammerzeit** [comment]
can you post your `webpack.config.js`?

**Comment by bdefore** [comment]
here's my fork and branch i'm working from: https://github.com/bdefore/react-redux-universal-hot-example/tree/parameterized-routes-and-source-path

you should be able to test either case if you remove the line here https://github.com/bdefore/react-redux-universal-hot-example/blob/parameterized-routes-and-source-path/external/webpack-overrides-config.js#L8

**Comment by halt-hammerzeit** [comment]
ok
