### ISSUE TITLE
LESS asset renders in router components, but throws an `asset not found` error in Html component

### ISSUE THREAD

**Issue by jonlong** [halt-hammerzeit/webpack-isomorphic-tools#32]
Apologies if this is the wrong place to ask this question — I haven't had much luck elsewhere!

I've got an app based on the [Universal Hot Example](https://github.com/erikras/react-redux-universal-hot-example), and am getting `[error] asset not found` when attempting to `require()` a LESS file.

I've copied the [style-loader configuration](https://github.com/halt-hammerzeit/webpack-isomorphic-tools#style-loader-standard-css-stylesheets) from this repo, and confirmed that it's possible to render this file in components called by `react-router`. However, if I [render the file from an `Html` container component](https://github.com/jonlong/universal-webpack-troubleshooting/blob/master/src/components/Html.jsx#L53) (using the convention in your `Html` component [here](https://github.com/halt-hammerzeit/webpack-isomorphic-tools#mainjs)), the error is thrown.

I'm not sure if this is originating from Webpack Isomorphic Tools, or a configuration issue, or something else — but it's got me stumped. 

I've put together a quick example here that demonstrates what I'm seeing: https://github.com/jonlong/universal-webpack-troubleshooting

If you could point me in the right direction, I'd really appreciate it!

**Comment by halt-hammerzeit** [comment]
So, what asset exactly isn't found?
What are the contents of your `webpack-assets.json`?

**Comment by jonlong** [comment]
Here's the full error: `[webpack-isomorphic-tools] [error] asset not found: ./src/less/main.less`

The `styles` object in my `webpack-assets.json` is empty:

```
{
  "javascript": {
    "main": "/dist/main-f05038d9705e0f2a8a2c.js"
  },
  "styles": {},
  "assets": {}
}
```

**Comment by halt-hammerzeit** [comment]
Well, yeah, because Webpack never gets to your `html.js` and therefore it never sees that `require()` call and never adds that `./src/less/main.less` to assets.
Find a way to `require(./src/less/main.less)` in your Webpack code.
Or `require.ensure(./src/less/main.less)`

**Comment by jonlong** [comment]
Sorry, I don't quite understand what you mean when you say that Webpack "never gets to my `Html.js`". The pages renders the html correctly on request — it just doesn't include the assets. Is that a different thing entirely? 

If my `jsx` module loaders are configured to compile it ([see here](https://github.com/jonlong/universal-webpack-troubleshooting/blob/master/webpack/config.dev.js#L103-L109)) is that not enough?

**Comment by halt-hammerzeit** [comment]
Is `html.js` included in your Webpack build?
`module.loaders` only work for the files traceable from your entry point.

**Comment by jonlong** [comment]
AH, I understand now. That's why the assets in your webapp example are `require()`d here: https://github.com/halt-hammerzeit/webapp/blob/master/code/client/html%20assets.js

Which is then included by Webpack here: https://github.com/halt-hammerzeit/webapp/blob/master/webpack/webpack.config.js#L57

That makes sense! Thanks for the help!

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
