### ISSUE TITLE
Paths created with template strings are not found when require()d

### ISSUE THREAD

**Issue by jonlong** [halt-hammerzeit/webpack-isomorphic-tools#33]
In development mode, when using a template string to `require()` an asset like this:

```js
const shortcutIconDir = '../../public/images/icons/shortcuts';

require(`${shortcutIconDir}/76.png`);
```

The `asset not found` error is raised. However, passing the literal string like so:

```js
require('../../public/images/icons/shortcuts/76.png');
```

Successfully adds the asset to the `webpack-assets.json` manifest.

Here's a repo where the error can be reproduced: https://github.com/jonlong/universal-webpack-troubleshooting

And these are the lines in question: https://github.com/jonlong/universal-webpack-troubleshooting/blob/master/src/components/App.jsx#L8-L12

**Comment by halt-hammerzeit** [comment]
Of course it won't work because Webpack doesn't allow it. It can't know
what package or file to include in the build if it's a variable and not a
simple string

**Comment by isomoar** [comment]
@halt-hammerzeit 
I am puzzled a little by your answer. What about Webpack `context` option? https://github.com/webpack/docs/wiki/context
Example in doc looks like exactly what @jonlong wants to do.

**Comment by halt-hammerzeit** [comment]
@isomoar Ok, seems that Webpack really supports dynamic `require()`.
That's an interesting solution.
Anyway, I'm not planning on implementing support for dynamic `require()` myself (but if anyone needs that kind of support that much then they can always create a Pull Request).
