### ISSUE TITLE
Cannot read property './webpack-assets.json' of undefined

### ISSUE THREAD

**Issue by happypoulp** [halt-hammerzeit/webpack-isomorphic-tools#35]
Hi,

I am using the json-loader and when I try to use webpack-isomorphic-tools I get this error server-side:

```
local ~/Codes/webpack-iso $ npm start
...
[require-hook] [debug] Loading source code for /Users/me/Codes/webpack-iso/webpack-assets.json
[webpack-isomorphic-tools] [debug] require() called for /Users/me/Codes/webpack-iso/webpack-assets.json
[webpack-isomorphic-tools] [debug]  requiring ./webpack-assets.json
/Users/me/Codes/webpack-iso/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/index.js:345
		var asset = assets[asset_path];
		                  ^

TypeError: Cannot read property './webpack-assets.json' of undefined
    at webpack_isomorphic_tools.asset_source (/Users/me/Codes/webpack-iso/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/index.js:345:21)
    at webpack_isomorphic_tools.require (/Users/me/Codes/webpack-iso/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/index.js:327:70)
    at /Users/me/Codes/webpack-iso/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/index.js:294:18
...
```

I have created a repo with minimal code to reproduce the issue here: https://github.com/happypoulp/webpack-isomorphic

Here is the webpack config that I use: https://github.com/happypoulp/webpack-isomorphic/blob/master/webpack.config.js
and here is the webpack isomorphic tools config I use: https://github.com/happypoulp/webpack-isomorphic/blob/master/webpack-isomorphic-tools.config.js

The webpack compilation is running well and the `webpack-assets.json` actually exists so I don't understand what I'm missing. May that be an issue with webpack-isomorphic-tools?

Thanks for your help.

**Comment by halt-hammerzeit** [comment]
Ha ha, interesting bug you found.
So, what it does is it intercepts all `require(.json)`s and tries to load those Json files from `webpack-assets.json`.
I've updated the package.
The new version should fix the error, try it.

**Comment by happypoulp** [comment]
Works perfectly! Just for curiosity, how does it come that I did not reproduce this issue in the well known universal example (that is also using the json-loader): https://github.com/erikras/react-redux-universal-hot-example ? I can't figure it out what I did differently to trigger the issue...

Thanks a lot for `webpack-isomorphic-tools` and for your quick fix!

**Comment by halt-hammerzeit** [comment]
@happypoulp because they're not using "json" asset extension
https://github.com/erikras/react-redux-universal-hot-example/blob/master/webpack/webpack-isomorphic-tools.js#L15

**Comment by happypoulp** [comment]
I see now. I did not understood that the `assets` of webpack-isomorphic-tools config was the one that triggered handling of `require` by webpack-isomorphic-tools server-side .

Thanks!

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
