### ISSUE TITLE
Setting up initial cache before starting the server

### ISSUE THREAD

**Issue by mhahn** [halt-hammerzeit/webpack-isomorphic-tools#39]
I just started deploying an universal app using these tools.

I've noticed that the first request after I deploy is really slow, then subsequent requests are fast.

From this: https://github.com/halt-hammerzeit/webpack-isomorphic-tools/issues/17 I'm guessing it has to do with building that initial cache. Is there a way I can trigger building this before the server starts?

I'm using these tools via:

```
var WebpackIsomorphicTools = require('webpack-isomorphic-tools');
global.webpackIsomorphicTools = new WebpackIsomorphicTools(require('../webpack/webpack-isomorphic-tools'))
    .development(__LOCAL__)
    .server(rootDir, function() {
        require('../src/server');
    });
```

**Comment by halt-hammerzeit** [comment]
try `2.2.22`.
I haven't checked if it fixes the issue but it should

**Comment by halt-hammerzeit** [comment]
Or it shouldn't.
Most likely your initial latency is caused not by loading `webpack-assets.json` but by `require()`ing all the assets inside the first `render()`.
In that case you can issue a `.render()` call when your server has started to case all your asset `require()`s

**Comment by mhahn** [comment]
yea `2.2.22` didn't seem to do anything. i think its definitely the time to `require` assets initially.

i haven't dug too much into your library yet, but do you have a recommendation for where that `render` call would go?

with client side only webpack, i know that it starts at the entry point and resolves everything from there. what is the equivalent on the server side with your toolset? i'm using an architecture similar to: https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/server.js

**Comment by halt-hammerzeit** [comment]
I think the `.render()` call would go somewhere there

```
var WebpackIsomorphicTools = require('webpack-isomorphic-tools');
global.webpackIsomorphicTools = new WebpackIsomorphicTools(require('../webpack/webpack-isomorphic-tools'))
    .development(__LOCAL__)
    .server(rootDir, function() {
        require('../src/server');
        require('http').request({ host, port, path });
    });
```

**Comment by mhahn** [comment]
Would I just render the root component? Or does it need to be the getRoutes?

**Comment by halt-hammerzeit** [comment]
I guess you can try to render the routes which are "slow" the first time as you said.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example

**Comment by ilionic** [comment]
@halt-hammerzeit is there available any migration tips / guideline from `webpack-isomorphic-tools` to `universal-webpack`? Thanks

**Comment by halt-hammerzeit** [comment]
There's no migration since these aren't two different major versions of a single tools but rather two completely different tools.
Start from scratch.

**Comment by ilionic** [comment]
Thanks! Am I understanding correctly that `unversal-webpack` would solve issue of slow initial cache since it's making pre-build of assets?
