### ISSUE TITLE
"asset not found" Error while file is present in webpack-assets.json

### ISSUE THREAD

**Issue by happypoulp** [halt-hammerzeit/webpack-isomorphic-tools#40]
Hi,

I came across this issue and I am not sure if it's due to the unusual folder structure of my project or if it's a bug from webpack-isomorphic-tools.

The issue can be reproduced on https://github.com/happypoulp/webpack-isomorphic/tree/issue-production

After running `npm run webpack` if you run `npm start` to start the application server, you'll see errors being emitted by webpack-isomorphic tools about some assets not being found.

Here is the debug output:

```
.local ~/Codes/webpack-iso > npm start

> webpack-iso@1.0.0 start /Users/fbonnefont/Codes/webpack-iso
> NODE_ENV=dev node app/bin/server.js

[webpack-isomorphic-tools] [debug] instantiated webpack-isomorphic-tools with options {
  "debug": true,
  "assets": {
    "json": {
      "extensions": [
        "json"
      ]
    },
    "scss": {
      "extensions": [
        "scss"
      ]
    }
  },
  "webpack_assets_file_path": "webpack-assets.json",
  "webpack_stats_file_path": "webpack-stats.json"
}
[webpack-isomorphic-tools] [debug] entering development mode
[webpack-isomorphic-tools] [debug] registering require() hooks for assets
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.json
[require-hook] [debug] Hooking into *.json files loading
[require-hook] [debug] -----------------------------------------------
[require-hook] [debug] Overriding an already existing require() hook
[require-hook] [debug] for file extension .json
[require-hook] [debug] -----------------------------------------------
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.scss
[require-hook] [debug] Hooking into *.scss files loading
FAKE SERVER
[webpack-isomorphic-tools] [debug] flushing require() caches
[require-hook] [debug] require() hook fired for /Users/fbonnefont/Codes/webpack-iso/app/src/base.scss
[webpack-isomorphic-tools] [debug] require() called for /Users/fbonnefont/Codes/webpack-iso/app/src/base.scss
[webpack-isomorphic-tools] [debug]  requiring ./src/base.scss
[require-hook] [debug] require() hook fired for /Users/fbonnefont/Codes/webpack-iso/app/webpack-assets.json
[require-hook] [debug] Fallback to original loader
[webpack-isomorphic-tools] [error] asset not found: ./src/base.scss
[require-hook] [debug] require() hook fired for /Users/fbonnefont/Codes/webpack-iso/app/src/mod-1.scss
[webpack-isomorphic-tools] [debug] require() called for /Users/fbonnefont/Codes/webpack-iso/app/src/mod-1.scss
[webpack-isomorphic-tools] [debug]  requiring ./src/mod-1.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/mod-1.scss
[require-hook] [debug] require() hook fired for /Users/fbonnefont/Codes/webpack-iso/app/src/file.json
[webpack-isomorphic-tools] [debug] require() called for /Users/fbonnefont/Codes/webpack-iso/app/src/file.json
[webpack-isomorphic-tools] [debug]  requiring ./src/file.json
[webpack-isomorphic-tools] [error] asset not found: ./src/file.json
...
```

What puzzles me is that for example `./src/base.scss` is actually present in webpack-assets.json but under the path `./app/src/base.scss`... The project_base_path I gave to webpack-isomorphic-tools server is the same as the one used in my webpack.config.js as suggested in your docs but I think that the issue might come from that setup.

Do you know what the issue could come from?

Thanks!

**Comment by halt-hammerzeit** [comment]
Post your `webpack-assets.json`.
What is your `project_base_path`?
You can also post your `webpack-stats.json` as a gist.

**Comment by happypoulp** [comment]
Here is my `webpack-assets.json`:
```
{
  "javascript": {
    "main": "/static/main.js"
  },
  "styles": {},
  "assets": {
    "./app/src/file.json": {
      "some_key": "some value",
      "bool": true,
      "arr": [
        1,
        2,
        3
      ]
    },
    "./app/src/base.scss": [
      [
        "/Users/fbonnefont/Codes/webpack-iso/app/app/src/base.scss.webpack-module",
        "body {\n  font: 100% Georgia, sans-serif;\n  color: #333;\n  background: #aaa; }\n",
        ""
      ]
    ],
    "./app/src/mod-1.scss": [
      [
        "/Users/fbonnefont/Codes/webpack-iso/app/app/src/mod-1.scss.webpack-module",
        "p {\n  background: red; }\n",
        ""
      ]
    ]
  }
}
```

And the project_base_path I provided is: `/Users/fbonnefont/Codes/webpack-iso/app`

Here is the gist for `webpack-stats.json`: https://gist.github.com/happypoulp/41ed82d7076ea411e46e

Thanks!

**Comment by halt-hammerzeit** [comment]
So, you have in webpack stats:

```
    {
      "id": 7,
      "identifier": "/Users/fbonnefont/Codes/webpack-iso/node_modules/style-loader/index.js!/Users/fbonnefont/Codes/webpack-iso/node_modules/css-loader/index.js!/Users/fbonnefont/Codes/webpack-iso/node_modules/sass-loader/index.js!/Users/fbonnefont/Codes/webpack-iso/app/src/mod-1.scss",
      "name": "./app/src/mod-1.scss",
```

For some reason Webpack lists your files relative to `/Users/fbonnefont/Codes/webpack-iso/` folder.
I don't know why is that so.

**Comment by happypoulp** [comment]
Thanks, I get no idea either why webpack is doing so. Is there any way I can configure webpack-isomorphic-tools to workaround that webpack weirdness?

**Comment by halt-hammerzeit** [comment]
Well, you can always ask in the webpack repo why is it doing so.
Or you can write your own `path` parsers but I think that's the wrong way to go: it would work but it's fighting consequences.

**Comment by happypoulp** [comment]
I see, thanks!

**Comment by happypoulp** [comment]
Ok after a bit of digging I found something but I am not sure how I should interpret it :).

Basically the stats file that you retrieve from webpack at https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/plugin.js#L135 is not the same as the one you would retrieve by running the CLI command `webpack --config some.webpack.config.js --json`. This last one seems to produce "correct" modules paths but the one retrieved through NodeJS webpack plugin doesn't.

I guess there is some real webpack issue here about the way the stats JSON is produced  before being returned to the plugin "done".

**Comment by happypoulp** [comment]
I opened an issue in webpack: https://github.com/webpack/webpack/issues/1778 and I was informed that there is a `context` parameter available for `toJSON` method. I think that there is some customization that should be made when calling `stats.toJSON` [here](https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/plugin.js#L135).

I tried:
```javascript
var json = stats.toJson(
  context: webpack_configuration.context
});
```
in https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/plugin.js but it does not seems to work (with code above some assets does not appears in `webpack-assets.json`).

Here is an example I made to highlight the use of `context` in `stats.toJSON` to fix wrong paths in stats: https://github.com/happypoulp/webpack-isomorphic/commit/264e4eaa389caf9526d29e2daed15246cf33c157

Hope this helps!

**Comment by halt-hammerzeit** [comment]
Oh, so your directory structure is as follows

```
.
├── README.md
├── app
│   ├── dist
│   ├── src
│   └── webpack.config.js
├── node_modules
│   └── webpack
└── package.json
```

Then it's clear why the paths contain the `./app` prefix: it's because your `node_modules` are one level higher that the `app` folder.

So, are `webpack-stats` correct when output in your `webpack.config.js`?
https://github.com/happypoulp/webpack-isomorphic/commit/264e4eaa389caf9526d29e2daed15246cf33c157

**Comment by halt-hammerzeit** [comment]
It has a mention of `options.context` in the sources and seems that it should work
https://github.com/webpack/webpack/blob/a3837b779a7bddf95d2ab6e9d217a1db197fe746/lib/Stats.js#L32

You can try to add that code to your `node_modules/webpack-isomorphic-tools/babel_compiled_modules/plugin/plugin.js`

```
console.log('@@@@@@@@@@@@@@@@', webpack_configuration.context)
var json = stats.toJson(
  context: webpack_configuration.context
});
```

And then see if the generated `webpack-stats.json` have the correct path.

**Comment by halt-hammerzeit** [comment]
If it works in your case when you make the changes denoted above then I'll include these changes in a new release.

**Comment by happypoulp** [comment]
I tried this code:
```javascript
console.log('@@@@@@@@@@@@@@@@', webpack_configuration.context)
var json = stats.toJson({
  context: webpack_configuration.context
});
```
in this branch: https://github.com/happypoulp/webpack-isomorphic/tree/issue-production but while `webpack-stats.json` contains correct paths, it seems to break another behavior of the app: scss files are no more added to `webpack-assets.json`...

`webpack-assets.json` *without* code above:
```
{
  "javascript": {
    "main": "/static/main.js"
  },
  "styles": {},
  "assets": {
    "./app/src/file.json": {
      "some_key": "some value",
      "bool": true,
      "arr": [
        1,
        2,
        3
      ]
    },
    "./app/src/base.scss": [
      [
        "/Users/classtar/Codes/webpack-iso/app/app/src/base.scss.webpack-module",
        "body {\n  font: 100% Georgia, sans-serif;\n  color: #333;\n  background: #aaa; }\n",
        ""
      ]
    ],
    "./app/src/mod-1.scss": [
      [
        "/Users/classtar/Codes/webpack-iso/app/app/src/mod-1.scss.webpack-module",
        "p {\n  background: red; }\n",
        ""
      ]
    ]
  }
}
```

`webpack-assets.json` *with* code above:
```
{
  "javascript": {
    "main": "/static/main.js"
  },
  "styles": {},
  "assets": {
    "./src/file.json": {
      "some_key": "some value",
      "bool": true,
      "arr": [
        1,
        2,
        3
      ]
    }
  }
}
```
webpack-stats.json: https://gist.github.com/happypoulp/3ef47e984c2bc4cdcd1c

and my config for webpack-isomorphic-tools is:
```javascript
var WebpackIsomorphicToolsPlugin = require('webpack-isomorphic-tools/plugin');

module.exports = {
  debug: true,
  assets: {
    json: {
      extensions: ['json']
    },
    scss: {
      extensions: ['scss'],
      path: WebpackIsomorphicToolsPlugin.style_loader_path_extractor,
      filter: WebpackIsomorphicToolsPlugin.style_loader_filter,
    },
  }
}
```
webpack-stats.json: https://gist.github.com/happypoulp/ab0210fc813ceb09a6df

**Comment by halt-hammerzeit** [comment]
Yes, that's because `css` assets are not detected now.

https://gist.github.com/happypoulp/3ef47e984c2bc4cdcd1c#file-webpack-stats-with-patch-json-L143
```
    {
      "id": 3,
      "identifier": "/Users/classtar/Codes/webpack-iso/node_modules/css-loader/index.js!/Users/classtar/Codes/webpack-iso/node_modules/sass-loader/index.js!/Users/classtar/Codes/webpack-iso/app/src/base.scss",
      "name": "../~/css-loader!../~/sass-loader!./src/base.scss",
```

While 
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/plugin.js#L198
```
Plugin.style_loader_filter = function(module, regular_expression, options, log)
{
	return regular_expression.test(module.name) && module.name.indexOf('./~/css-loader') === 0
}
```

So it's not `./~/css-loader` and is `../~/css-loader` now.

Possible solutions:

* Write your own `filter` for `scss`
* Rewrite `Plugin.style_loader_filter` so that it works in both cases (make it more generic)
* Maybe generate the correct path to `css-loader` based on some info

**Comment by halt-hammerzeit** [comment]
I can suggest you use this filter function:

```
function(module, regular_expression, options, log)
{
	return regular_expression.test(module.name) && module.name.split('!')[0].indexOf('/~/css-loader') >= 0
}
```

If it works for you then I'll make it the default one

**Comment by happypoulp** [comment]
Thanks, it works perfectly!

I made a PR: https://github.com/halt-hammerzeit/webpack-isomorphic-tools/pull/41.

Should the fix for the filter function be made in webpack-isomorphic-tools too or should I keep it in my app?

**Comment by halt-hammerzeit** [comment]
Okay, try it out
`npm install webpack-isomorphic-tools@2.2.24 --save`

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example

**Comment by AndrewRayCode** [comment]
I know this library is deprecated and I can't tell if this is the same issue, but after upgrading to Webpack 4 I'm getting lots of

```
[webpack-isomorphic-tools] [error] asset not found
```

repeated for all of my css imports

and a huge stack trace starting with:

```
[0] [webpack-isomorphic-tools/plugin] [error] TypeError: require(...) is not a function
[0]     at Object.<anonymous> (containers/Game/Game.scss.webpack-module:2:87)
```
