### ISSUE TITLE
Reasoning behind stats info always being output to the console

### ISSUE THREAD

**Issue by tanem** [halt-hammerzeit/webpack-isomorphic-tools#45]
Hey there. Just wondering what the reasoning was for always [outputting stats info to the console when in development mode](https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/plugin.js#L145)?

I'm using `webpack-dev-server` and have certain aspects of it's stats output switched off, but when I'm using this plugin I have no control over it's stats output, meaning I get duplication/more noise in my console. e.g.:

```
Hash: 23256a845beab320f89e
Version: webpack 1.12.11
Time: 1783ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.44 MB       0  [emitted]  main
Time: 1783ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.44 MB       0  [emitted]  main
webpack: bundle is now VALID.
```

Do you think it would be a good idea to allow control of this plugins stats output via a configuration option, perhaps similar to [the one exposed for `webpack-dev-server`](http://webpack.github.io/docs/webpack-dev-server.html#api)? Or have I missed something in the docs or with how this plugin works? :smirk:

Cheers!

**Comment by halt-hammerzeit** [comment]
try `npm install webpack-isomorphic-tools@latest --save`

**Comment by tanem** [comment]
Thanks for the quick turnaround. Unfortunately the commit didn't fix things, I'm guessing because of the following?

- `plugin.options.development` is still the only thing being checked prior to stats output on [this line](https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/plugin.js#L145)
- `plugins.options.verbosity` isn't defaulting to `false` [as mentioned in the README](https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/README.md#configuration).

PS happy to have a go at a PR if that's going to be helpful :sunglasses:

**Comment by halt-hammerzeit** [comment]
So are you seeing green Webpack stats every time you save a file when in development mode?

**Comment by tanem** [comment]
Hmm, only on initial startup now actually. Once hot reloading is happening I don't see the double up any more. Will have a closer look today, unless you beat me to it :wink:

**Comment by halt-hammerzeit** [comment]
Well, because I've changed the code in this release:
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/notify%20stats.js#L14

If you come up with further suggestions you can post them here

**Comment by tanem** [comment]
Ah right, I see now. Thanks for the clarification!

Yeh personally I still don't like the fact that we can have a falsy `verbose` setting, yet we'll still always see the stats output on the first run, resulting in a double up. At the moment I'm not sure if that initial output is adding any value, since it's just outputting verbatim what the `webpack-dev-server` will output eventually anyway, plus we have no way of controlling exactly what's output like we do with `webpack-dev-server`.

If `verbose` had the equivalent behaviour of [webpack's `quiet`](https://webpack.github.io/docs/webpack-dev-server.html#webpack-dev-server-cli), plus there was a `stats` config option or something where we could control exactly what stats were output, that would make more sense to me.

However, I'm still wondering if this plugin even needs to bother with the stats output at all, perhaps it's a concern that should be left to other parts of the webpack build process? There could well be gaps in my understanding of webpack plugin development and webpack's build process in general though, so interested to hear your thoughts :)

**Comment by halt-hammerzeit** [comment]
The same output can be achieved with Webpack standard settings but it also outputs the list of all the files in the bundle (about a thousand of them) and that's a lot of mess.

If you find a way to stop Webpack from outputting that list of all the files in the bundle then still it will output the green stats every time you save a file which is also too much as you've already pointed out.

So, I don't see how `verbose` flag can be superseeded by Webpack standard flags.

**Comment by tanem** [comment]
Just to clarify, the only reason I mentioned wrangling the `verbose` behaviour was in case you were set on leaving console output in the plugin.

My real question is: do we even need to have console output at all, since webpack does it anyway once it's finished compilation? If not, then you might be able to delete a bunch of code.

Thanks for your time anyway, I'll leave this alone for now :)

**Comment by halt-hammerzeit** [comment]
`do we even need to have console output at all`

Console output is used for debugging and is enabled by `debug` flag.
By default it doesn't output anything apart from the initial info.

`since webpack does it anyway once it's finished compilation?`

As I've described in the previous comment, Webpack's output logic is different from the current logic of `webpack-isomorphic-tools`.
If you find a way to make those identical then the output may be disabled.

**Comment by sikhote** [comment]
Thanks for an awesome solution for webpack.

Would you consider a PR that added in the option to control, in some way, the initial compilation output? From the previous comments above my understanding is that there is not a method for that. Thanks for any info.

**Comment by halt-hammerzeit** [comment]
> Would you consider a PR that added in the option to control, in some way, the initial compilation output? 

What do you mean exactly

**Comment by sikhote** [comment]
Possibly on [this line](https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/plugin.js#L139) adding another check for an additional option, which would completely silence the initial build output. Perhaps there's another way—I couldn't figure one out.

**Comment by halt-hammerzeit** [comment]
So, you're willing to have absolutely no output from webpack?
You may add an option if you like (+ test/index.js for that option)

**Comment by sikhote** [comment]
Yes, that's the goal (except for errors). Gulp is good enough for notifying me when a task has started or completed. Do you have a preference for a function (allowing customized output) or another option that would completely disable it? Function is preferred from my point of view. Thanks for the input.

**Comment by halt-hammerzeit** [comment]
Can't say like that, specifics is needed

**Comment by sikhote** [comment]
Keeping [this line](https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/plugin.js#L139) in mind, something along the lines of:
```
const isFunction = obj => !!(obj && obj.constructor && obj.call && obj.apply);

// output some info to the console if in development mode
if (plugin.options.development)
{
   if(isFunction(plugin.options.statsLogger)) {
      // if custom stats logger was passed in as and option
      // and it is a valid function, then execute with
      plugin.options.statsLogger(stats, json, plugin.options.verbose)
   } else {
      // outputs stats info to the console
      // (only needed in development mode)
      notify_stats(stats, json, plugin.options.verbose)
   }
}
```
Hopefully that's about how the option could be passed and it is helpful for understanding. isFunction was sourced from [here](http://stackoverflow.com/questions/5999998/how-can-i-check-if-a-javascript-variable-is-function-type).

**Comment by halt-hammerzeit** [comment]
@sikhote How would you use this logger? Do you need such a function and for what purpose?

**Comment by sikhote** [comment]
@halt-hammerzeit I would use it with gulp-util (preffered to console.log) to output that the inital build has completed, but nothing more. Currently all of this is console.log'ed:

<img width="797" alt="screen shot 2016-04-22 at 8 21 35 am" src="https://cloud.githubusercontent.com/assets/6610596/14746219/64efa92c-0863-11e6-9f4d-21a2a715e90b.png">

**Comment by halt-hammerzeit** [comment]
ok, do it.
the option name will be `print_stats` in the source code, you can still name it `printStats` in your configuration.
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/plugin.js#L16

don't forget to fix the tests after you add this option.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example

**Comment by sikhote** [comment]
@halt-hammerzeit I would consider this no longer needed with the `verbosity` option.

**Comment by halt-hammerzeit** [comment]
@sikhote Yeah, I guess so. The reasoning behind the `verbosity` commit was that people using [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard) said they needed no output.
