### ISSUE TITLE
Breaking random node modules

### ISSUE THREAD

**Issue by mmahalwy** [halt-hammerzeit/webpack-isomorphic-tools#5]
I always have random node modules breaking and cannot get request, superagent to work

Here is an example
```
Users/mmahalwy/Desktop/quran/quran.com-frontend/node_modules/keen-js/src/core/index.js:4
var previous_Keen = root.Keen;
                        ^
TypeError: Cannot read property 'Keen' of undefined
    at Object.<anonymous> (/Users/mmahalwy/Desktop/quran/quran.com-frontend/node_modules/keen-js/src/core/index.js:2:25)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/mmahalwy/Desktop/quran/quran.com-frontend/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mmahalwy/Desktop/quran/quran.com-frontend/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mmahalwy/Desktop/quran/quran.com-frontend/node_modules/keen-js/src/server/index.js:1:12)
    at Module._compile (module.js:460:26)
```

**Comment by halt-hammerzeit** [comment]
@mmahalwy so, have you resolved the issue? what was the cause of the error?

**Comment by halt-hammerzeit** [comment]
From what I can see
https://github.com/keen/keen-js/blob/master/src/core/index.js#L1-L2

```javascript
var root = 'undefined' !== typeof window ? window : this;
var previous_Keen = root.Keen;
```

Because it's not window, `this` seems to be undefined.
That's weird.
Are you still having the issue?

**Comment by mmahalwy** [comment]
I found the issue, it's REALLY weird.... but 

GOOD: 
```
require('app-module-path').addPath(__dirname);
require('app-module-path').addPath('./src/scripts');

require("babel/register")({
	stage: 0,
	plugins: ["typecheck"]
});

global.__CLIENT__ = false;
global.__SERVER__ = true;

if (process.env.NODE_ENV !== "production") {
	if (!require("piping")({hook: true})) {
		return;
	}
}
```

BAD:
```
delete process.env.BROWSER;

require('app-module-path').addPath(__dirname);
require('app-module-path').addPath('./src');

require("babel/register")({
	stage: 0,
	ignore: /\.scss$/
});

global.__CLIENT__ = false;
global.__SERVER__ = true;

// if (process.env.NODE_ENV !== "production") {
// 	if (!require("piping")({hook: true})) {
// 		return;
// 	}
// }
//
```

**Comment by mmahalwy** [comment]
I don't understand why it was breaking but ya... the first works, the second breaks everything

**Comment by halt-hammerzeit** [comment]
Well, to begin with, if you do 
```
require("babel/register")({
    stage: 0,
    ignore: /\.scss$/
});
```
then it means that you `require()` .scss files in your code (which you do because you use `webpack-isomorphic-tools` for that).
but if `webpack-isomorphic-tools` really worked then `require(*.scss)` calls wouldn't reach Babel at all which means that if you find yourself adding such hacks to babel configuration then it means `webpack-isomorphic-tools` is not set up correctly in your app.

Possible reasons are: 

not calling `.server()` method
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#mainjs

absend 'scss' extension
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#webpack-isomorphic-tools-configurationjs

**Comment by halt-hammerzeit** [comment]
If you give me the complete code maybe I could spot a bug

**Comment by mmahalwy** [comment]
@halt-hammerzeit https://github.com/mmahalwy/react-fluxible-starter/blob/master/start.js

And I agree with you the ignoring scss was prior to adding your tool

**Comment by halt-hammerzeit** [comment]
Ok, I can reproduce the error: the `global` (`this`) object is undefined when I run `npm run start`.
I'll debug it a bit.

**Comment by halt-hammerzeit** [comment]
@mmahalwy 
So, I removed the `, ignore: /\.scss$/` line and it works now.

Can you do that in your code and confirm that it works?

**Comment by mmahalwy** [comment]
yeah i have and confirmed it works... which is really weird why that happens no? :S

**Comment by halt-hammerzeit** [comment]
I don't know too.
But it doesn't matter now since it's all by the book now.

**Comment by mmahalwy** [comment]
yep! Thank you sir for an awesome plugin!
