### ISSUE TITLE
should allow empty string as publicPath

### ISSUE THREAD

**Issue by jchip** [halt-hammerzeit/webpack-isomorphic-tools#60]
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/plugin/plugin.js#L122

**Comment by halt-hammerzeit** [comment]
Why would `publicPath` be empty?
Is there a valid use case when it's empty?

**Comment by jchip** [comment]
When we use CDN, it generate a unique path for the files, so it's better to use empty string.  That allow us to compile style files with URL as the file only without any path, so they will load correctly as relative URL.

**Comment by jchip** [comment]
Actually, webpack doesn't require publicPath to be defined at all.  Is there any reason this plugin requires it?

**Comment by halt-hammerzeit** [comment]
Give me an example of your style where there's a correct path

**Comment by jchip** [comment]
//CDN.sample.com/<hash>/

That's how a CDN url looks like.  Generated after webpack and files uploaded.

Why does this plugin require publicPath while webpack itself doesn't?

**Comment by jchip** [comment]
//CDN.sample.com/(hash)/

**Comment by halt-hammerzeit** [comment]
I don't recognize `//CDN.sample.com/(hash)/` as a valid URL.
Valid urls usually have the form of `http(s)://...`

**Comment by jchip** [comment]
That URL would just assume the protocol of the main page.

**Comment by halt-hammerzeit** [comment]
ok, so you have in your code
```
require('//CDN.sample.com/(hash)/style.css')
```
I don't see how it might even compile in webpack

**Comment by jchip** [comment]
No, I don't have that in my code.

Can we focus on why you need publicPath?

**Comment by halt-hammerzeit** [comment]
What do you have in your code then?

**Comment by jchip** [comment]
Why do you think that empty string is not a valid value for publicPath?  It's valid.

**Comment by halt-hammerzeit** [comment]
For what use case is it valid?

**Comment by jchip** [comment]
I am not sure how to answer that.  It's valid just like any other value you might use for publicPath.  What use case is it invalid.

**Comment by jchip** [comment]
Since webpack just prepend `publicPath` to the file name, the URL that goes into your page generally ends up like this: `<publicPath><filename>`.  The value `""` is as valid as any other value such as `"/assets/"`, doesn't really matter what your use case is.

However, here is the long reason why it's valid:

Now, as we know, this is how browser resolves URLs in a page.

Say when you load a page from `<protocol>://<hostname>/<path>`, such as `http://sample.com/test/index.html`, if in the page, you have the following links:

```html
<img src="http://absolute.com/foo/bar/1.jpg" />
<img src="//resolve_protocol.com/foo/bar/2.jpg" />
<img src="/full_path/foo/bar/3.jpg" />
<img src="relative_path/4.jpg" />
<img src="5.jpg" />
```

The browser will resolve those links to the following full URLs:

  * `1.jpg` - `http://absolute.com/foo/bar/1.jpg`
  * `2.jpg` - `http://resolve_protocol.com/foo/bar/2.jpg`
  * `3.jpg` - `http://sample.com/full_path/foo/bar/3.jpg`
  * `4.jpg` - `http://sample.com/test/relative_path/4.jpg`
  * `5.jpg` - `http://sample.com/test/5.jpg`

So now if I use an empty string `""` for `publicPath`, then for any file webpack needs to export, it will generate the relative URL as `"<filename>"`, such as `bundle.js`, and that will be embedded as the url.

When my page is finally loaded into the browser, say from the full URL `http://mypage.com/app`, then any link to the files would be resolved according the above rules.  For the file `bundle.js`, the URL webpack generates would be `bundle.js` given `publicPath` is `""`, and it will be resolved according to the rule for the file `4.jpg` above.

**Comment by halt-hammerzeit** [comment]
So what you are saying is you have `require('bundle.js')` in your javascript code, but these `require()` calls don't need to be resolved because they are precompiled by Webpack and it will be like
```
// bundle.js
function webpack_module_123() {}
...
webpack_module_123()
```
And you don't need to resolve any URLs for that

**Comment by jchip** [comment]
I am simply saying that `""` is a valid value for webpack `publicPath` config, and in fact, webpack allows you to skip specifying that at all and would use empty string if it's not defined, and unless you have a very specific reason for your plugin, you should not alter that behavior.  And you should have some explanation why `""` is not a valid value for webpack's `publicPath` config.  I've given you a very detailed explanation on why it's valid.

**Comment by halt-hammerzeit** [comment]
So suppose you have ```background-image: require('../../images/logo.png')``` in your CSS file, then Webpack outputs this logo as `/home/user/project/build/a8fsd8752340fdsfl3246c5.png`.
Then it outputs the compiled CSS which has ```background-image: url(${publicPath}a8fsd8752340fdsfl3246c5.png)```.
Why wouldn't you want a `publicPath` there? It is safer to use absolute URLs than using relative URLs.
You could set your `publicPath` to `/assets/` and it would work.

**Comment by jchip** [comment]
> Then it outputs the compiled CSS which has background-image: `url(${publicPath}a8fsd8752340fdsfl3246c5.png)`.

Sure, and if `publicPath` is `""`, that becomes `url(a8fsd8752340fdsfl3246c5.png)`.  Is there a problem with that?

If you want use case, take any project that use webpack, change `publicPath` in its webpack config to `""` and that's your use case.

**Comment by halt-hammerzeit** [comment]
> Sure, and if publicPath is "", that becomes url(a8fsd8752340fdsfl3246c5.png). Is there a problem with that?

I think that's not the right approach and it's better to have absolute paths in stylesheets than relative paths like this.
I see no valid reason why one shouldn't use absolute paths.

**Comment by jchip** [comment]
this is not about what you think URL in stylesheet should be.  It's about whether `""` can be a valid value in webpack config.

**Comment by halt-hammerzeit** [comment]
This is not about what you think URL in stylesheet should be. It's about the right way to do the whole thing. Closing the issue as unconstructive.

**Comment by halt-hammerzeit** [comment]
Implemented and released

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
