### ISSUE TITLE
Compatibility with Webpack DLL Plugins?

### ISSUE THREAD

**Issue by trueter** [halt-hammerzeit/webpack-isomorphic-tools#62]
I've been trying to reduce the webpack build times on my setup and tried to implement the DLL Plugins as outlined by `vjpr` here: https://github.com/erikras/react-redux-universal-hot-example/issues/616

Compilation works well, but when starting the application, I get these cryptic errors associated to any `.scss` files I require.
Is something wrong with my `wepack-isomorphic-tools` configuration? Or do you think the problem arises from somewhere else?

Error:
```
[0] 2e806729f506f9eebf83b7fd00853881.png  27.4 kB          [emitted]  
[0]                           app.dll.js  4.43 MB       0  [emitted]  app
[0] /Users/yyyyy/xxxxx/xxxxx-react/src/components/Cover/Cover.scss.webpack-module:2
[0] exports = module.exports = require("./../../../node_modules/css-loader/lib/css-base.js")();
[0]                                                                                         ^
[0] 
[0] TypeError: require(...) is not a function
[0]     at Object.<anonymous> (/Users/yyyyy/xxxxx/xxxxx-react/src/components/Cover/Cover.scss.webpack-module:2:89)
[0]     at Module._compile (module.js:413:34)
[0]     at Object._module3.default._extensions.(anonymous function) [as .webpack-module] (/Users/yyyyy/xxxxx/xxxxx-react/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:264:11)
[0]     at Module.load (module.js:357:32)
[0]     at Function.Module._load (module.js:314:12)
[0]     at Module.require (module.js:367:17)
[0]     at require (internal/module.js:16:19)
[0]     at populate_assets (/Users/yyyyy/xxxxx/xxxxx-react/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:375:31)
[0]     at Object.write_assets [as default] (/Users/yyyyy/xxxxx/xxxxx-react/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:63:2)
[0]     at Compiler.<anonymous> (/Users/yyyyy/xxxxx/xxxxx-react/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/plugin.js:175:27)
```

Config:
```js
module.exports = {
    assets: {
        // ...
        scss: {
            extensions: [ 'scss' ],
            filter: function( module, regex, options, log ) {
                if(  options.development ) {
                    return WebpackIsomorphicToolsPlugin.style_loader_filter( module, regex, options, log )
                } else {
                    return regex.test( module.name )
                }
            },
            path: function( module, options, log ) {
                if( options.development ) {
                    return WebpackIsomorphicToolsPlugin.style_loader_path_extractor( module, options, log )
                } else {
                    return module.name
                }
            },
            parser: function( module, options, log ) {
                if( options.development ) {
                    return WebpackIsomorphicToolsPlugin.css_modules_loader_parser( module, options, log )
                } else {
                    return module.source
                }
            }
        }
    }
}
```

Loader:
```js
{ 
    test: /\.scss$/, 
    loader: 'style!css?module&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap&' 
},
```

Thanks!

**Comment by halt-hammerzeit** [comment]
I don't know what that error means.
https://github.com/webpack/css-loader/blob/master/lib/css-base.js
The require(..) should return a function accoriding to the code.

Maybe that's because of that "DLL" feature which I don't know what it is and how it works.

**Comment by trueter** [comment]
Thanks for looking into it.

**Comment by halt-hammerzeit** [comment]
@trueter I was googling for `webpack-isomorphic-tools` this weekend, as usual, lol. (that's the way I find out what problems people have with it: blog posts, stackoverflow, etc)
Also found your slides:
http://www.slideshare.net/trueter/how-to-make-your-webpack-builds-10x-faster
An huge amount of research you've done.
And I can see that you managed to run the tools with this DLL thing?
Just so that other people getting here from google would know.

**Comment by trueter** [comment]
Hey! Yeah, I managed to throw time at the problem until it worked.

The DLL plugins allow you to create static libraries that contain vendor code that rarely changes. Because you no longer have to rebuild that code everytime you save something, you can significantly reduce the incremental build time during development.
The big gotcha with using `webpack-isomorphic-tools` together with DLL bundles is related to the `webpack-assets.json`.
Using DLLs requires two seperate webpack processes being executed sequentially. The first one prepares static assets, the second one sets up your hot development environment as usual. 
In my solution I am using the `webpackIsomorphicToolsPlugin` in the first step (missing from slides).  

In most tutorials you will find people only setting up chunks that contain vendor code in the first step. 
But not including your own code in the first step's chunks will cause `write_assets` to miss these modules. I believe this caused the above problem. So I added the app chunk to the first build step as well. 

But now some paths in the `webpack-assets.json` had the wrong host. They were all pointing to where the static files lived, but soem needed to load custom code from the `webpack-dev-server`. AFAIK `webpack-isomorphic-tools` infers the path from the `publicPath` config option. Changing that `publicPath` broke more more links then it fixed and in the end I ended up manually hacking the path like this: `assets.javascript.app = path.replace( '3000', '3001' ).replace( '.dll.', '.' )`.

**Comment by halt-hammerzeit** [comment]
Thanks for the instructions. Maybe some people will find them useful.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
