### ISSUE TITLE
Error: cannot find module

### ISSUE THREAD

**Issue by skleeschulte** [halt-hammerzeit/webpack-isomorphic-tools#65]
When I try to require a css file on the server, I get `Error: cannot find module './Abc.css'`. This is my setup:

    project_root
    |-node_modules
    |-src
    | |-components
    | | |-Abc.js
    | | |-Abc.css
    | | '-...
    | |-webpack
    | | |-config.js
    | | '-isomorphic-tools-config.js
    | |-client.js
    | |-server.js
    | '-...
    |-transpiled
    '-...

This is my run configuration:

1. Transpile all files from `src` to `transpiled`.
2. Start `webpack-dev-server` cli in project_root with `--config transpiled/webpack/config.js`. Webpack context is set to `project_root`. The entry point is set to `./src/client.js`. `webpack_assets_file_path` in `isomorphic-tools-config.js` is set to `path.join(__dirname, 'webpack-assets.json')`, so this will be `C:/.../project_root/transpiled/webpack/webpack-assets.json`.
3. Start webserver with `node transpiled/server.js`.

This is working very well, excep that I cannot get server side requiring of css-files to work. `webpack-assets.json` is generated and placed in the configured path (`transpiled/webpack`). The file `Abc.css` is required in `components/Abc.js` with `require('./Abc.css');` This is the content of webpack-assets.json:

    {
      "javascript": {
        "app": "/assets/app-48766c500b763e9145f7.js"
      },
      "styles": {},
      "assets": {
        "./src/components/Abc.css": ".red { color: red; }"
      }
    }

I also tried to manually adjust the path in webpack-assets.json (e.g. replacing `src` with `transpiled`), but I always get `Error: cannot find module './Abc.css'`. The error comes from `C:\...\project_root\node_modules\require-hacker\babel-transpiled-modules\require hacker.js:403:34` and with debug output I can see the following lines:

    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.css
    [require-hook] [debug] Hooking into *.css files loading

So I think `webpack-isomorphic-tools` get correctly initialized on the server and correctly "capture" the require call to the css-file, but cannot find the entry in `webpack-assets.json`. Any help appreciated! What could be the error here? Thank you!

**Comment by halt-hammerzeit** [comment]
The assets seem to be resolved relative to the `src` folder:
```
  "assets": {
    "./src/components/Abc.css": ".red { color: red; }"
  }
```
And that's the case because this file is generated by the Webpack plugin and webpack is set up with the `./src/client.js` entry point.

Why are you transpiling your code before running it?

**Comment by skleeschulte** [comment]
I transpile the code because it's written in ES6 (ok, that's obvious). I don't use the require hook because I need the js files and source map files on the disc so that debugging in the IDE works. I also transpile `isomorphic-tools-config.js` because it's `required()` by the server and I found it to be cleaner to have it all in the same place (that is `transpiled`).

I also tried to manually replace `"./src/components/Abc.css"` in `webpack-assets.json` with `"./transpiled/components/Abc.css"`, but I get the same error. What should the entry look like with the mentioned file structure and webpack context configured to `C:/../project_root` also the working directory being this directory?

**Comment by halt-hammerzeit** [comment]
Oh, and IDE, I see...
Post your debug logs - it will tell you more info.

**Comment by skleeschulte** [comment]
These logs?

    [webpack-isomorphic-tools] [debug] instantiated webpack-isomorphic-tools v2.2.44 with options {
      "debug": true,
      "webpack_assets_file_path": "C:\\dev\\project_root\\transpiled\\webpack\\webpack-assets.json",
      "webpack_stats_file_path": "C:\\dev\\project_root\\transpiled\\webpack\\webpack-stats.json",
      "assets": {
        "images": {
          "extensions": [
            "png",
            "jpg",
            "gif",
            "ico",
            "svg"
          ]
        },
        "styles": {
          "extensions": [
            "css"
          ]
        }
      }
    }
    [webpack-isomorphic-tools] [debug] entering development mode
    [webpack-isomorphic-tools] [debug] registering require() hooks for assets
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.png
    [require-hook] [debug] Hooking into *.png files loading
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.jpg
    [require-hook] [debug] Hooking into *.jpg files loading
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.gif
    [require-hook] [debug] Hooking into *.gif files loading
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.ico
    [require-hook] [debug] Hooking into *.ico files loading
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.svg
    [require-hook] [debug] Hooking into *.svg files loading
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.css
    [require-hook] [debug] Hooking into *.css files loading
    [server] webpack-isomorphic-tools setup finished, starting server
    module.js:327
        throw err;
        ^
    
    Error: Cannot find module './Abc.css'
        at Function.Module._resolveFilename (module.js:325:15)
        at Function._module3.default._resolveFilename (C:\dev\project_root\node_modules\require-hacker\babel-transpiled-modules\require hacker.js:403:34)
        at Function.Module._load (module.js:276:25)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (C:\dev\project_root\transpiled\components\Abc.js:35:1)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)

BTW: Thank you very much for helping me so quick with this issue!!

**Comment by halt-hammerzeit** [comment]
You should enable `debug: true` flag in the configuration and then post the logs.

**Comment by skleeschulte** [comment]
Just did ;) (see above) - or do you mean something else?

**Comment by halt-hammerzeit** [comment]
Dunno.
Post your code from the transpiled folder (the file which requires `App.scss`)

**Comment by skleeschulte** [comment]
Ok, I created a repo with a sample project. The structure is the same as my original project, I only removed some webpack loaders and plugins:
[https://github.com/skleeschulte/webpack-isomorphic-tools-debugging](https://github.com/skleeschulte/webpack-isomorphic-tools-debugging)

I used webpack cli here instead of webpack dev server (because that's the important thing that needs to be working in production), and there are two changes which I don't understand now:

- The paths in [webpack-assets.json](https://github.com/skleeschulte/webpack-isomorphic-tools-debugging/blob/master/transpiled/webpack/webpack-assets.json) don't start with `./src/...` anymore, but now with `/assets/...`.
- The css is now in the `styles` section of webpack-assets.json, not the `assets` section.

However, the error message remains the same:

    [server] setting up webpack-isomorphic-tools
    [webpack-isomorphic-tools] [debug] instantiated webpack-isomorphic-tools v2.2.44
     with options {
      "debug": true,
      "webpack_assets_file_path": "C:\\dev\\project_root\\transpiled\\webpack\\webpa
    ck-assets.json",
      "webpack_stats_file_path": "C:\\dev\\project_root\\transpiled\\webpack\\webpac
    k-stats.json",
      "assets": {
        "images": {
          "extensions": [
            "png",
            "jpg",
            "gif",
            "ico",
            "svg"
          ]
        },
        "styles": {
          "extensions": [
            "css"
          ]
        }
      }
    }
    [webpack-isomorphic-tools] [debug] entering production mode
    [webpack-isomorphic-tools] [debug] registering require() hooks for assets
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.png
    [require-hook] [debug] Hooking into *.png files loading
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.jpg
    [require-hook] [debug] Hooking into *.jpg files loading
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.gif
    [require-hook] [debug] Hooking into *.gif files loading
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.ico
    [require-hook] [debug] Hooking into *.ico files loading
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.svg
    [require-hook] [debug] Hooking into *.svg files loading
    [webpack-isomorphic-tools] [debug]  registering a require() hook for *.css
    [require-hook] [debug] Hooking into *.css files loading
    [server] webpack-isomorphic-tools setup finished, starting server
    module.js:341
        throw err;
        ^
    
    Error: Cannot find module './Abc.css'
        at Function.Module._resolveFilename (module.js:339:15)
        at Function._module3.default._resolveFilename (C:\dev\project_root\node_modu
    les\require-hacker\babel-transpiled-modules\require hacker.js:403:34)
        at Function.Module._load (module.js:290:25)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.<anonymous> (C:\dev\project_root\transpiled\components\Abc.js:3:1)
    
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)

The transpiled file that contains the failing require statement is here: [https://github.com/skleeschulte/webpack-isomorphic-tools-debugging/blob/master/transpiled/components/Abc.js](https://github.com/skleeschulte/webpack-isomorphic-tools-debugging/blob/master/transpiled/components/Abc.js)

**Comment by skleeschulte** [comment]
Ok, I just found out another thing: It looks like the css file has to exist in the place where the "normal" node require looks for it. Babel only creates the .js and .map files in the output directory (`transpiled`). The css is not copied from src to transpiled. When I copy the css file from src to transpiled, the error message changes from the already mentioned

    Error: Cannot find module './Abc.css'

to

    [webpack-isomorphic-tools] [error] asset not found: ./transpiled/components/Abc.css

I thought the file does not need to exist because its content is already in the `webpack-assets.json` file. But now I see that this is not always true. Can you explain when the css file content will be in webpack-assets.json and when not? And when will the css be in the assets section of webpack-assets.json and when will it be in the styles section?

**Comment by halt-hammerzeit** [comment]
```
{"javascript":{"app":"/assets/app-cdb1b2ccc17656f6f571.js"},"styles":{"app":"/assets/styles-0cec3223d19f0342d64edd73a8d374bb.css"},"assets":{}}
```

Those aren't file extension assets, those are the reserved "javascript" and "styles" assets used in page markup (`<html/>`).
The assets themselves are absent as you can read from the JSON because of ExtractTextPlugin.

**Comment by halt-hammerzeit** [comment]
```javascript
/**
 * Setup webpack isomorphic tools
 */
console.log('[server] setting up webpack-isomorphic-tools');
var isomorphicTools = new _webpackIsomorphicTools2.default(_isomorphicToolsConfig2.default).development(_env2.default.DEVELOPMENT).server(_context2.default, function () {
    console.log('[server] webpack-isomorphic-tools setup finished, starting server');
    process.nextTick(afterIsomorphicToolsSetup); // nextTick so that isomorphicTools will be set
});

/**
 * Setup server side rendering and start server
 */
function afterIsomorphicToolsSetup() {
```

Ha ha, that won't work.
That's why the documentation explicitly says to put your server code into a separate file.
Do that and then it will work.
Post back.

**Comment by halt-hammerzeit** [comment]
> Ok, I just found out another thing: It looks like the css file has to exist in the place where the "normal" node require looks for it. Babel only creates the .js and .map files in the output directory (transpiled). The css is not copied from src to transpiled. When I copy the css file from src to transpiled, the error message changes from the already mentioned

I doesn't have to be there.
On the contrary, it should not be there because it's taken from the void.

**Comment by halt-hammerzeit** [comment]
Oh, no, my statement seems to be wrong: the file must exist.

**Comment by halt-hammerzeit** [comment]
The reason for that is that's how Node.js's internal require works.
https://github.com/nodejs/node/blob/master/lib/module.js#L336
That can possibly be changed but that would require some R&D so if anyone wants do dive into `module.js` they can try to experiment with it.

**Comment by halt-hammerzeit** [comment]
(closing the issue since it's resolved)

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
