### ISSUE TITLE
Resolving scss in node_modules

### ISSUE THREAD

**Issue by sampeka** [halt-hammerzeit/webpack-isomorphic-tools#66]
Hey @halt-hammerzeit, I'm trying to use [React Toolbox](http://react-toolbox.com/) isomorphically but they have scss in their distribution - which means that webpack isomorphic tools needs to resolve the scss in the `node_modules` folder. They have an open ticket for it here: https://github.com/react-toolbox/react-toolbox/issues/160

The problem is webpack-isomorphic-tools doesn't seem to be resolving any of the files in the node_modules folder:

```
[webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-toolbox/lib/app/style.scss
[webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-toolbox/lib/ripple/style.scss
[webpack-isomorphic-tools] [error] asset not found: ./node_modules/react-toolbox/lib/menu/style.menu_item.scss
```

Is it possible that we can toggle this behaviour? And does this come with any caveats?

**Comment by halt-hammerzeit** [comment]
Hello.
Post your `webpack-assets.json` and we'll see if assets are there

**Comment by sampeka** [comment]
That was quick, thanks a lot!

```
{
  "javascript": {
    "main": "/static/main-6a8bad22087ed6df976f.js"
  },
  "styles": {
    "main": "/static/components.css"
  },
  "assets": {
    "./app/styles/components/DesktopNav.css": {
      "nav": "DesktopNav_nav_3sa",
      "overBar": "DesktopNav_overBar_I-W",
      "profileAndNotifications": "DesktopNav_profileAndNotifications_2A6",
      "navSearchBar": "DesktopNav_navSearchBar_KWX",
      "underBar": "DesktopNav_underBar_1Xu",
      "navLink": "DesktopNav_navLink_2C6",
      "_style": "#DesktopNav_nav_3sa {\n  background-color: white;\n}\n\n#DesktopNav_overBar_I-W {\n  height: 60px;\n  display: -webkit-box;\n  display: flex;\n  -webkit-box-pack: justify;\n          justify-content: space-between;\n  flex-wrap: nowrap;\n  -webkit-box-align: center;\n          align-items: center;\n  padding: 3px 20px;\n}\n\n#DesktopNav_overBar_I-W .logo {\n  width: 150px;\n}\n\n#DesktopNav_profileAndNotifications_2A6  {\n  display: -webkit-box;\n  display: flex;\n  flex-wrap: nowrap;\n  -webkit-box-align: center;\n          align-items: center;\n}\n\n#DesktopNav_profileAndNotifications_2A6 .profilePicture {\n  width: 50px;\n  height: 50px;\n  margin-left: 30px;\n}\n\n#DesktopNav_profileAndNotifications_2A6 .glyphicon {\n  font-size: 22px;\n}\n\n#DesktopNav_navSearchBar_KWX {\n  width: 50%;\n  position: relative;\n}\n\n#DesktopNav_navSearchBar_KWX input {\n  height: 40px;\n  background-color: #eee;\n  width: 100%;\n}\n\n#DesktopNav_navSearchBar_KWX .glyphicon {\n  position: absolute;\n  padding: 0 10px;\n  right: 0;\n  top: 12px;\n}\n\n#DesktopNav_underBar_1Xu {\n  border-top: 1px solid black;\n  display: -webkit-box;\n  display: flex;\n  -webkit-box-pack: center;\n          justify-content: center;\n  flex-wrap: nowrap;\n}\n\n.DesktopNav_navLink_2C6 {\n  padding: 10px 20px;\n}\n",
      "_content": [
        [
          51,
          "#DesktopNav_nav_3sa {\n  background-color: white;\n}\n\n#DesktopNav_overBar_I-W {\n  height: 60px;\n  display: -webkit-box;\n  display: flex;\n  -webkit-box-pack: justify;\n          justify-content: space-between;\n  flex-wrap: nowrap;\n  -webkit-box-align: center;\n          align-items: center;\n  padding: 3px 20px;\n}\n\n#DesktopNav_overBar_I-W .logo {\n  width: 150px;\n}\n\n#DesktopNav_profileAndNotifications_2A6  {\n  display: -webkit-box;\n  display: flex;\n  flex-wrap: nowrap;\n  -webkit-box-align: center;\n          align-items: center;\n}\n\n#DesktopNav_profileAndNotifications_2A6 .profilePicture {\n  width: 50px;\n  height: 50px;\n  margin-left: 30px;\n}\n\n#DesktopNav_profileAndNotifications_2A6 .glyphicon {\n  font-size: 22px;\n}\n\n#DesktopNav_navSearchBar_KWX {\n  width: 50%;\n  position: relative;\n}\n\n#DesktopNav_navSearchBar_KWX input {\n  height: 40px;\n  background-color: #eee;\n  width: 100%;\n}\n\n#DesktopNav_navSearchBar_KWX .glyphicon {\n  position: absolute;\n  padding: 0 10px;\n  right: 0;\n  top: 12px;\n}\n\n#DesktopNav_underBar_1Xu {\n  border-top: 1px solid black;\n  display: -webkit-box;\n  display: flex;\n  -webkit-box-pack: center;\n          justify-content: center;\n  flex-wrap: nowrap;\n}\n\n.DesktopNav_navLink_2C6 {\n  padding: 10px 20px;\n}\n",
          ""
        ]
      ]
    },
    "./app/styles/components/Logo.css": {
      "_style": ".logo img {\n   width: 100%;\n}\n",
      "_content": [
        [
          52,
          ".logo img {\n   width: 100%;\n}\n",
          ""
        ]
      ]
    },
    "./app/styles/components/ProfilePicture.css": {
      "_style": ".profilePicture img {\n  width: 100%;\n}\n",
      "_content": [
        [
          53,
          ".profilePicture img {\n  width: 100%;\n}\n",
          ""
        ]
      ]
    },
    "./app/static/images/default-avatar.png": "/static/419f75147610c11aa3e68528a769b58f.png",
    "./app/static/images/icon-logo.png": "/static/5a34a280063a2a48416de3ea2ed719d9.png",
    "./app/static/images/large-logo.png": "/static/d88768cbd7e314e9c7c0fc8293b3cb83.png"
  }
}
```

**Comment by halt-hammerzeit** [comment]
Well, it's not there.
The reason might be that it isn't `require()`d in the code.
Are those styles `require()`d somewhere in the code?
If not then Webpack won't bundle them.

**Comment by sampeka** [comment]
It's required in their code, in the distributed version. So they provide you with untranspiled `scss` and leave it to you to finalize the build. See https://github.com/react-toolbox/react-toolbox/issues/437#issuecomment-207996639

**Comment by halt-hammerzeit** [comment]
Ok, if it's required in their code then it's in `webpack-stats.json`.
Post you stats.

**Comment by sampeka** [comment]
Turns out I'm just bad at reading. All I needed to do was include `node_modules` in the config as per your readme, thanks a lot for the help and sorry about the time wasting ;)

    scss: {
      extensions: ['scss'],

      include: [/^\.\/node_modules\/*/],

      filter (module, regex, options, log) {
        return plugin.styleLoaderFilter(module, regex, options, log);
      },

      path (module, options, log) {
        return plugin.styleLoaderPathExtractor(module, options, log);
      },

      parser (module, options, log) {
        return plugin.cssModulesLoaderParser(module, options, log);
      }
    },

**Comment by halt-hammerzeit** [comment]
Hmm, okay, I thought is was going to include everything with `include` omitted.
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/blob/master/source/index.js#L441-L448
Anyway, feel free to ask any related question in this thread.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example

**Comment by ngoctranfire** [comment]
So I've been trying to include react-toolbox, and my webpack configuration file is like this, but it doesn't seem to work for the server-side rendering part. Can someone help me with this?

`var WebpackIsomorphicToolsPlugin = require('webpack-isomorphic-tools/plugin');
const { ASSET_FILE } = require('./paths');

// see this link for more info on what all of this means
// https://github.com/halt-hammerzeit/webpack-isomorphic-tools
module.exports = {

  // when adding "js" extension to asset types
  // and then enabling debug mode, it may cause a weird error:
  //
  // [0] npm run start-prod exited with code 1
  // Sending SIGTERM to other processes..
  //
  // debug: true,
  webpack_assets_file_path: ASSET_FILE,
  assets: {
    images: {
      extensions: [
        'jpeg',
        'jpg',
        'png',
        'gif'
      ],
      parser: WebpackIsomorphicToolsPlugin.url_loader_parser
    },
    fonts: {
      extensions: [
        'woff',
        'woff2',
        'ttf',
        'eot'
      ],
      parser: WebpackIsomorphicToolsPlugin.url_loader_parser
    },
    svg: {
      extension: 'svg',
      parser: WebpackIsomorphicToolsPlugin.url_loader_parser
    },
    style_modules: {
      extensions: ['less','scss'],
      include: [/^\.\/node_modules\/*/],
      filter: function(module, regex, options, log) {
        if (options.development) {
          // in development mode there's webpack "style-loader",
          // so the module.name is not equal to module.name
          return WebpackIsomorphicToolsPlugin.style_loader_filter(module, regex, options, log);
        } else {
          // in production mode there's no webpack "style-loader",
          // so the module.name will be equal to the asset path
          return regex.test(module.name);
        }
      },
      path: function(module, options, log) {
        if (options.development) {
          // in development mode there's webpack "style-loader",
          // so the module.name is not equal to module.name
          return WebpackIsomorphicToolsPlugin.style_loader_path_extractor(module, options, log);
        } else {
          // in production mode there's no webpack "style-loader",
          // so the module.name will be equal to the asset path
          return module.name;
        }
      },
      parser: function(module, options, log) {
        if (options.development) {
          return WebpackIsomorphicToolsPlugin.css_modules_loader_parser(module, options, log);
        } else {
          // in production mode there's Extract Text Loader which extracts CSS text away
          return module.source;
        }
      }
    }
  }
};
`
