### ISSUE TITLE
ERROR in Cannot find module 'json5' && [webpack-isomorphic-tools] [error] asset not found

### ISSUE THREAD

**Issue by lewis617** [halt-hammerzeit/webpack-isomorphic-tools#72]
ERROR in Cannot find module 'json5'
 @ ./common/components/Counter.js 63:23-59
[webpack-isomorphic-tools] [error] asset not found: ./common/assets/images/Plus.png

webpack-assets.json
```
{
  "javascript": {
    "main": "/static/bundle.js"
  },
  "styles": {},
  "assets": {}
}
```
webpack.config.js
```

var path = require('path')
var webpack = require('webpack')
var Webpack_isomorphic_tools_plugin = require('webpack-isomorphic-tools/plugin')

var webpack_isomorphic_tools_plugin =
    // webpack-isomorphic-tools settings reside in a separate .js file
    // (because they will be used in the web server code too).
    new Webpack_isomorphic_tools_plugin(require('./webpack-isomorphic-tools-configuration'))
    // also enter development mode since it's a development webpack configuration
    // (see below for explanation)
        .development();

module.exports = {
    devtool: 'inline-source-map',
    entry: [
        'webpack-hot-middleware/client',
        './client/index.js'
    ],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/static/'
    },
    plugins: [
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin(),
        webpack_isomorphic_tools_plugin
    ],
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel',
                exclude: /node_modules/,
                include: __dirname,
                query: {
                    optional: ['runtime'],
                    stage: 2,
                    env: {
                        development: {
                            plugins: [
                                'react-transform'
                            ],
                            extra: {
                                'react-transform': {
                                    transforms: [
                                        {
                                            transform: 'react-transform-hmr',
                                            imports: ['react'],
                                            locals: ['module']
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            },
            {
                test: webpack_isomorphic_tools_plugin.regular_expression('images'),
                loader: 'url-loader?limit=10240', // any image below or equal to 10K will be converted to inline base64 instead
            }
        ]
    }
}

```

**Comment by halt-hammerzeit** [comment]
Post your `./webpack-isomorphic-tools-configuration`

**Comment by lewis617** [comment]
webpack-isomorphic-tools-configuration.js

```
import Webpack_isomorphic_tools_plugin from 'webpack-isomorphic-tools/plugin'

export default
{
  assets:
  {
    images:
    {
      extensions: ['png', 'jpg', 'gif', 'ico', 'svg']
    }
  }
}
```


I try to add webpack-isomorphic-tools to the Redux example,but I got the problem above:
https://github.com/reactjs/redux/tree/master/examples/universal

**Comment by halt-hammerzeit** [comment]
The configuration seems ok.
You can try to add `console.log('===========', require('./common/assets/images/Plus.png'))` to `./client/index.js` and report back the result.

**Comment by halt-hammerzeit** [comment]
Also you can try to add `debug: true` flag to `webpack-isomorphic-tools-configuration.js` and post the output here.

**Comment by lewis617** [comment]
> redux-universal-example@0.0.0 start /home/lewis/code/react-redux-tutorial/redux-examples/universal
> node server/index.js

[webpack-isomorphic-tools] [debug] instantiated webpack-isomorphic-tools v2.2.48 with options {
  "debug": true,
  "assets": {
    "images": {
      "extensions": [
        "png",
        "jpg",
        "gif",
        "ico",
        "svg"
      ]
    }
  },
  "webpack_assets_file_path": "webpack-assets.json",
  "webpack_stats_file_path": "webpack-stats.json"
}
[webpack-isomorphic-tools] [debug] entering production mode
[webpack-isomorphic-tools] [debug] registering require() hooks for assets
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.png
[require-hook] [debug] Hooking into *.png files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.jpg
[require-hook] [debug] Hooking into *.jpg files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.gif
[require-hook] [debug] Hooking into *.gif files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.ico
[require-hook] [debug] Hooking into *.ico files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.svg
[require-hook] [debug] Hooking into *.svg files loading
[webpack-isomorphic-tools] [debug] (/home/lewis/code/react-redux-tutorial/redux-examples/universal/webpack-assets.json not found)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] [debug] (/home/lewis/code/react-redux-tutorial/redux-examples/universal/webpack-assets.json not found)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] [debug] (/home/lewis/code/react-redux-tutorial/redux-examples/universal/webpack-assets.json not found)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
 



loop and loop   not found

**Comment by lewis617** [comment]
```
> redux-universal-example@0.0.0 start /home/lewis/code/react-redux-tutorial/redux-examples/universal
> node server/index.js

[webpack-isomorphic-tools] [debug] instantiated webpack-isomorphic-tools v2.2.48 with options {
  "debug": true,
  "assets": {
    "images": {
      "extensions": [
        "png",
        "jpg",
        "gif",
        "ico",
        "svg"
      ]
    }
  },
  "webpack_assets_file_path": "webpack-assets.json",
  "webpack_stats_file_path": "webpack-stats.json"
}
[webpack-isomorphic-tools] [debug] entering production mode
[webpack-isomorphic-tools] [debug] registering require() hooks for assets
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.png
[require-hook] [debug] Hooking into *.png files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.jpg
[require-hook] [debug] Hooking into *.jpg files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.gif
[require-hook] [debug] Hooking into *.gif files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.ico
[require-hook] [debug] Hooking into *.ico files loading
[webpack-isomorphic-tools] [debug]  registering a require() hook for *.svg
[require-hook] [debug] Hooking into *.svg files loading
[webpack-isomorphic-tools] [debug] (/home/lewis/code/react-redux-tutorial/redux-examples/universal/webpack-assets.json not found)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] [debug] (/home/lewis/code/react-redux-tutorial/redux-examples/universal/webpack-assets.json not found)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] [debug] (/home/lewis/code/react-redux-tutorial/redux-examples/universal/webpack-assets.json not found)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
```

**Comment by halt-hammerzeit** [comment]
and, what does it output when you render your component with the image?

**Comment by halt-hammerzeit** [comment]
if it loops indefinitely then read this section for troubleshooting
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#infinite-waiting-for-the-first-webpack-build-to-finish

**Comment by lewis617** [comment]
> you aren't running your Webpack build either in parallel with your app or prior to running you app
> you're using webpack-dev-middleware inside your main server code which you shouldn't

I think problem is this,   this tools should be used in a server , and webpack dev server should be another .

**Comment by halt-hammerzeit** [comment]
Ok, then you just need to run your webpack build and after that `webpack-assets.json` will be generated

**Comment by lewis617** [comment]
If you like, you can write a simple demo base on redux  example，https://github.com/reactjs/redux/tree/master/examples/universal

maybe helpful to learn to use this tools

**Comment by halt-hammerzeit** [comment]
Well, these tools aren't bound to Redux or anything like that.
They aren't bound to React either.
Their only dependence is Webpack.

**Comment by lewis617** [comment]
en ,  I should learn to use it  flexibly

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
