### ISSUE TITLE
__webpack_hmr cannot be found

### ISSUE THREAD

**Issue by Joodysen** [halt-hammerzeit/webpack-isomorphic-tools#77]
Hello,
I run the project on port 3002 while I running a webpack-dev-server on port 3003.
When I start the project it send `http://localhost:3002/__webpack_hmr` continuously and show `GET /__webpack_hmr 404` ,but I need it send `http://localhost:3003/__webpack_hmr`.I don't know how to realize,could you please give me any suggestion?

webpack-dev-server.js
```
var Express = require('express');
var webpack = require('webpack');

var webpackConfig = require('./dev.config.js');
var compiler = webpack(webpackConfig);

var host = 'localhost';
var port = 3003;
var serverOptions = {
  contentBase: 'http://' + host + ':' + port,
  quiet: true,
  noInfo: true,
  hot: true,
  inline: true,
  lazy: false,
  publicPath: webpackConfig.output.publicPath,
  headers: {'Access-Control-Allow-Origin': '*'},
  stats: {colors: true}
};

var app = new Express();

app.use(require('webpack-dev-middleware')(compiler, serverOptions));
app.use(require('webpack-hot-middleware')(compiler));

app.listen(port, function onAppListening(err) {
  if (err) {
    console.error(err);
  } else {
    console.info('==> Webpack development server listening on port %s', port);
  }
});
```

webpack.config.js:
```
module.exports = {
    context: path.resolve(__dirname, '..'),
    entry: [
        'webpack-hot-middleware/client?path=http://localhost:3003/__webpack_hmr',
        path.resolve(__dirname, '../src/client/index.js')
    ],
    resolve: {
        extensions: ['', '.js', '.jsx']
    },
    output: {
        path: path.resolve(__dirname, '../static/dist'),
        filename: '[name]-[hash].js',
        publicPath: 'http://localhost:3003/'
    },
    module: {
        loaders: [
            {
                test: /\.(js|jsx)$/,
                loader: 'babel',
                exclude: /node_modules/,
                query: {
                    presets: ['es2015', 'react']
                }
            },
            {
                test: /\.css$/, // Only .css files
                 loader: 'style!css'
            },
            {
                test: /\.scss$/,
                loader: 'style!css!sass?modules&localIdentName=[name]__[local]-[hash:base64:5]'
            }
        ]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        webpackIsomorphicToolsPlugin.development()
    ]
};
```

Thank u very much.

**Comment by halt-hammerzeit** [comment]
Hello.
This question is not related to the tools.
Refer to the numerous webpack-dev-server examples on the internet.
Remove the tools until you get it working without the tools.
Then you can include the tools in your bundle.

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
