### ISSUE TITLE
Consider using a naming convention more "Javascripty"

### ISSUE THREAD

**Issue by romulof** [halt-hammerzeit/webpack-isomorphic-tools#80]
Sorry, but your code feels like a python library 😜 

`sendEmailToAdmins` -> Javascript
`send_email_to_admins` -> Python

I strongly advise using ESLint with Airbnb profile: https://github.com/airbnb/javascript

It's very strict, even annoying, but in the end it's worthy.

**Comment by halt-hammerzeit** [comment]
And I don't like your skin tone.
Strongly advise being born a white man.

![https://gatasnegrasbrasileiras.files.wordpress.com/2014/11/negro-branco-1907.jpg?w=507&h=722]

It's difficult to achieve, but in the end it's worthy.
