### ISSUE TITLE
Can't use imports-loader with webpack-isomorphic-tools

### ISSUE THREAD

**Issue by jvorcak** [halt-hammerzeit/webpack-isomorphic-tools#83]
Hi,

I can't make `imports-loader` https://github.com/webpack/imports-loader work with `webpack-isomorphic-tools`. I'm not sure if this is the right place to report this bug. But, in projects where I use webpack-isomorphic-tools I can't get even this simple expression working

`Error: Cannot find module 'imports?config=>{size:50}!./example.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function._module3.default._resolveFilename (/Users/janvorcak/WebstormProjects/debugging-project/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:403:34)`

Is it possible that it's a bug in webpack-isomorphic-tools or maybe `require-hacker`?

**Comment by halt-hammerzeit** [comment]
I would suggest you try `universal-webpack`
https://github.com/halt-hammerzeit/universal-webpack

As for the `Cannot find module` error, post you config and your webpack-stats.json

**Comment by jvorcak** [comment]
@halt-hammerzeit thanks for a quick reply. I've just cloned este https://github.com/este/este and tried to import something using imports-loader. The problem is that I try to stay in sync with este stack master, so I can't easily switch to universal-webpack. Is universal-webpack supposed to be a replacement of webpack-universal-tools? Are there any drawbacks of switching to it?

**Comment by halt-hammerzeit** [comment]
`universal-webpack` is feature complete as opposed to the tools which aren't.
maybe the tools can work with the `imports-loader`.
To find that out you should post the tools config and webpack-stats.json
