### ISSUE TITLE
Можно самый простой пример реализации?

### ISSUE THREAD

**Issue by bORm** [halt-hammerzeit/webpack-isomorphic-tools#85]
По сабжу, без всяких сложных вложенностей и редаксов, только реакт + реакт роутер и простой html компонент
я пробую уже какой раз сделать его, и ниче не выходит
кроме того что я вижу около часа эту фразу в консоли
`[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)`

**Comment by halt-hammerzeit** [comment]
Читайте ридми в таком случае
