### ISSUE TITLE
Do I have to reload my server process on every build?

### ISSUE THREAD

**Issue by NSLS** [halt-hammerzeit/webpack-isomorphic-tools#87]
Hello, I have been using this plugin for quite a while and it has been working absolutely great. However, in our environment, we have always been killing the original node server and then starting it once again on every build cycle to achieve the updated state on the server. 

This method creates a problem of a downtime for the time until the node server starts if using single server environment. And by looking though the API of webpack-isomorphic-tools, I have seen a `refresh()` method, which allows to dynamically refresh the assets paths on every build. Unfortunately, by trying this out, I've faced a restriction, which allows using `refresh()` only in development mode.

So my question is, what's the problem with allowing dynamic path refresh in production mode?

Thanks.

**Comment by halt-hammerzeit** [comment]
Hello.
I can see what you're saying.
My opinion is that `.refresh()` is meant for develpoment only and that fully relaunching in production is the way to go.
Some people set up docker and start a new container, and then switch it from the old one once the http server has launched.
I'm not planning on permitting `refresh()` in production.
