### ISSUE TITLE
Objects are not valid as a react child

### ISSUE THREAD

**Issue by vpanjganj** [halt-hammerzeit/webpack-isomorphic-tools#88]
Hi, I receive this React error this when I send my first get request in production:
"Invariant Violation: Objects are not valid as a React child (found: object with keys {status, statusText, headers, config, request, data}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Home`."
My Home component totally works fine when I don't use `webpack-isomorphic-tools`

**Comment by halt-hammerzeit** [comment]
Yes, that's because you have `{object}` in your code, where `object` is `{status, statusText, headers, config, request, data}`
