### ISSUE TITLE
putting chunkhash as parameter in output filename cause javascript assets to be empty

### ISSUE THREAD

**Issue by eladlevy** [halt-hammerzeit/webpack-isomorphic-tools#89]
I've beed using the following output config in my webpack.conf file:
```javascript
output: {
 filename: "[name].js?v=[chunkhash]",
 publicPath: '/static/dist/',
 path: __dirname + "/dist"
}
```

and the output of my webpack-assets.json is:
` "javascript":{}`

It took me hours to realise that was the issue. the fix was simply changing filename to:
`filename: "[name]-[chunkhash].js"`

Is it a bug? or it's just me doing weird stuff with hash and file names

**Comment by halt-hammerzeit** [comment]
```
output.filename

Specifies the name of each output file on disk. You must not specify an absolute path here! The output.path option determines the location on disk the files are written to, filename is used solely for naming the individual files.
```

Why would you have "?" in a filename anyway?

**Comment by eladlevy** [comment]
Just to keep the file names more clean and still enjoy the benefits of cache busting.

**Comment by halt-hammerzeit** [comment]
Then I would use some other character instead of `?`
