### ISSUE TITLE
Changing relative path of webpack-assets

### ISSUE THREAD

**Issue by mmahalwy** [halt-hammerzeit/webpack-isomorphic-tools#91]
Given I am not compiling my server code, it used to be in `src/` but now is in `dist/`. That being said, webpack is still compiling and returning the webpack-assets.json to contain `./src/...`

Is there a way to configure things to be for `./dist` ? 

```
"assets":{"./src/containers/Login/style.scss": "..."}
```

**Comment by halt-hammerzeit** [comment]
Try "copy files" solution.
https://github.com/halt-hammerzeit/webpack-isomorphic-tools#cannot-find-module
Other than that, no known ways were found.
