### ISSUE TITLE
ProvidePlugin for automatic global variable importing

### ISSUE THREAD

**Issue by alecperkey** [halt-hammerzeit/webpack-isomorphic-tools#94]
[My fork of RRUHR](https://github.com/alecperkey/react-redux-universal-hot-example/commit/ecb5d2105f10b750792fba0ca6bf52ab619da898#diff-5f694022cd10cae14c85a89025b45c45R116) compiles, but doesn't recognize the 'global variables' ProvidePlugin provides.

```
 +    new webpack.ProvidePlugin({
 +      _: "underscore",
 +      m: "moment"
 +    }),
```

```
[0] C:\Users\User\WebstormProjects\react-redux-universal-hot-example\src\containers\About\About.js
[0]   17:17  error  "_" is not defined  no-undef
[0]   20:17  error  "m" is not defined  no-undef
[0] 
[0] ? 2 problems (2 errors, 0 warnings)
[0] 
[0] webpack built a5f41e035702768990ff in 22649ms
```

If I navigate to any router context which contains a reference to one of these variables (i.e. localhost:3000/about) , the server render fails:

```
[1] underscore:
[1] [piping] can't execute file: C:\Users\User\WebstormProjects\react-redux-universal-hot-example\bin\server.js
[1] [piping] error given was: ReferenceError: _ is not defined
[1]     at About.render (About.js:17:17)
```

**However**, if I navigate to other router context first, and _then_ navigate to /about, I can see the variables are in fact defined and work as desired.

[Requiring in server.js](https://github.com/alecperkey/react-redux-universal-hot-example/commit/80f08f711bd01e9ce6892efb7d8d5406f647a039#diff-8d44631bfd02d64ee75348ab92f466c0R8) solves the server render's reference error, yet I would prefer only router contexts which contain a reference in their component tree require these 'globals' (as ProvidePlugin behaves).

**Comment by alecperkey** [comment]
The benefit is I could have potentially hundreds of utility globals which would can be referenced without the redundancy of writing import 'thing' from 'thing-lib' and require('thing') across all the actual modules.

```
new webpack.ProvidePlugin({
      find: "lodash/find",
      map: 'lodash/map',
      m: "moment",
      l: "logger-library",
[...]
}),
```

**Comment by halt-hammerzeit** [comment]
Yeah, as stated in the README, `webpack-isomorphic-tools` doesn't support Webpack plugins.

> However, if I navigate to other router context first, and then navigate to /about, I can see the variables are in fact defined and work as desired.

Of course, because that's the client side, when you're navigating

> Requiring in server.js solves the server render's reference error, yet I would prefer only router contexts which contain a reference in their component tree require these 'globals' (as ProvidePlugin behaves).

Yeah, one could implement a feature where `webpack-isomorphic-tools` would detect `ProvidePlugin` and put those variables to `global` but that would be the same as you already do and wouldn't limit their scope only to depending modules.

**Comment by alecperkey** [comment]
I just read your readme for https://github.com/halt-hammerzeit/universal-webpack. Very awesome work, excited to start experimenting with it.

Do you think the ProvidePlugin could work with universal-webpack?

**Comment by alecperkey** [comment]
Or is what I'm seeking achieved by this part?

```
    exclude_from_externals:
    [
        'lodash-es',
        /^some-other-es6-only-module(\/.*)?$/
    ]`
```

**Comment by halt-hammerzeit** [comment]
> Do you think the ProvidePlugin could work with universal-webpack?

Yes, it works with every part of Webpack

> Or is what I'm seeking achieved by this part?

This `exclude_from_externals` parameter is just for ES6-only modules, i.e. the ones that will be processed by `babel-loader` too (webpack loader configuration required)
